'use client'
import type { EmergencyCase } from './cases'
import type { Discussion } from './discussions'

export default function POMRCaseView({item,discussion}:{item:EmergencyCase;discussion?:Discussion}){
 const list=(xs:string[])=> <ul className="pomr-list">{xs.map((x,i)=><li key={i}>{x}</li>)}</ul>
 return <div className="pomr-case">
  <section className="pomr-block"><div className="pomr-title">I. Identitas & Keluhan Utama</div><div className="pomr-grid two"><div><b>Case</b><span>{String(item.id).padStart(3,'0')}</span></div><div><b>Kategori</b><span>{item.category}</span></div><div><b>Diagnosis kerja</b><span>{item.diagnosis}</span></div><div><b>Prioritas</b><span>Emergensi</span></div></div><div className="pomr-sub"><b>Keluhan utama</b><p>{item.vignette.split('. ')[0]}.</p></div></section>
  <section className="pomr-block"><div className="pomr-title">II. Anamnesis</div><h4>Riwayat Penyakit Sekarang</h4><p>{item.vignette}</p><div className="pomr-grid two"><div><b>Riwayat penyakit dahulu</b><span>Komorbid dan faktor risiko yang tersedia pada kasus.</span></div><div><b>Obat & alergi</b><span>Data yang perlu dikonfirmasi.</span></div><div><b>Riwayat keluarga</b><span>Data relevan sesuai diagnosis banding.</span></div><div><b>Sosial & kebiasaan</b><span>Data relevan sesuai konteks.</span></div></div></section>
  <section className="pomr-block"><div className="pomr-title">III. Pemeriksaan Fisik</div><div className="pomr-grid two"><div><b>Pemeriksaan umum & tanda vital</b><span>{item.vitals}</span></div><div><b>Pemeriksaan sistematis</b><span>{item.exam}</span></div></div><div className="pomr-callout"><b>Primary survey</b><span>Airway → Breathing → Circulation → Disability → Exposure.</span></div></section>
  <section className="pomr-block"><div className="pomr-title">IV. Pemeriksaan Penunjang</div><p>{item.tests}</p><h4>Rencana pemeriksaan</h4>{list(['Pemeriksaan terarah sesuai masalah klinis.','Monitoring serial dan pemeriksaan lanjutan sesuai respons.','Pemeriksaan definitif tidak boleh menunda tindakan yang mendesak.'])}</section>
  <section className="pomr-block"><div className="pomr-title">V. Daftar Masalah</div>{list([item.diagnosis,`Risiko perburukan: ${item.redflags}`,`Diagnosis banding: ${item.ddx}`])}</section>
  <section className="pomr-block"><div className="pomr-title">VI. Pengkajian / Assessment</div><div className="assessment-card"><h4>Masalah 1 — {item.diagnosis}</h4><h5>Dipikirkan atas dasar</h5><p><b>Anamnesis:</b> {item.vignette}</p><p><b>Pemeriksaan fisik:</b> {item.vitals} {item.exam}</p><p><b>Pemeriksaan penunjang:</b> {item.tests}</p><h5>Analisis / clinical reasoning</h5>{list(discussion?.reasoning||[`Temuan klinis mendukung ${item.diagnosis}.`,`Diagnosis banding: ${item.ddx}.`])}</div><div className="assessment-card"><h4>Key clinical points</h4>{list(discussion?.keyPoints||[item.approach])}</div></section>
  <section className="pomr-block"><div className="pomr-title">VII. Rencana Diagnostik</div>{list([`Konfirmasi dan stratifikasi ${item.diagnosis}.`,'Evaluasi komplikasi sesuai kondisi.','Lakukan reassessment bila temuan berubah.'])}</section>
  <section className="pomr-block"><div className="pomr-title">VIII. Rencana Tatalaksana</div><div className="pomr-treatment"><b>Rencana utama</b><p>{item.treatment}</p></div><div className="pomr-sub"><b>Disposition</b><p>{item.disposition}</p></div></section>
  <section className="pomr-block"><div className="pomr-title">IX. Monitoring & Reassessment</div>{list(['Serial evaluasi kondisi klinis dan respons terhadap intervensi.','Dokumentasikan terapi, waktu, respons, dan efek samping.','Jika memburuk, ulangi penilaian sistematis dan evaluasi diagnosis banding.'])}<div className="pomr-danger"><b>RED FLAGS</b><span>{item.redflags}</span></div></section>
  <section className="pomr-block"><div className="pomr-title">X. Pitfall</div>{list(discussion?.pitfalls||['Jangan melewatkan kondisi yang mendesak.','Lakukan reassessment serial.'])}</section>
  <section className="pomr-block"><div className="pomr-title">XI. Kesimpulan / Ringkasan</div><p>{item.vignette} Temuan utama: {item.vitals}. {item.exam} Pemeriksaan: {item.tests} Diagnosis kerja: <b>{item.diagnosis}</b>.</p></section>
  <section className="pomr-block"><div className="pomr-title">XII. Prognosis & Evidence Base</div><div className="pomr-grid two"><div><b>Faktor prognosis</b><span>{item.redflags}</span></div><div><b>Guideline</b><span>{discussion?.guideline||'Verifikasi guideline diagnosis-spesifik terbaru dan protokol lokal.'}</span></div></div>{discussion?.guidelineUrl&&<a className="guideline-link" href={discussion.guidelineUrl} target="_blank" rel="noreferrer">Buka referensi resmi ↗</a>}</section>
 </div>
}
