'use client'

import { useMemo, useState } from 'react'
import ToolStyles from './ToolStyles'
import FluidGuide from './FluidGuide'

type Tool = 'bmi' | 'egfr' | 'crcl' | 'bsa' | 'gcs' | 'map' | 'shock' | 'anion' | 'correctedNa' | 'pedsFluid' | 'tpm'

const toolCards = [
  { id:'bmi' as Tool, icon:'⚖', title:'BMI', category:'General', desc:'Body mass index dari berat dan tinggi badan.' },
  { id:'bsa' as Tool, icon:'📐', title:'BSA', category:'General', desc:'Luas permukaan tubuh dengan Mosteller.' },
  { id:'egfr' as Tool, icon:'🫘', title:'eGFR CKD-EPI 2021', category:'Renal', desc:'Estimasi GFR berbasis kreatinin, usia, dan jenis kelamin.' },
  { id:'crcl' as Tool, icon:'🧪', title:'Creatinine Clearance', category:'Renal', desc:'Cockcroft–Gault untuk estimasi CrCl.' },
  { id:'gcs' as Tool, icon:'🧠', title:'GCS', category:'Emergency', desc:'Hitung Glasgow Coma Scale secara terstruktur.' },
  { id:'map' as Tool, icon:'♥', title:'MAP', category:'Emergency', desc:'Mean arterial pressure dari tekanan darah.' },
  { id:'shock' as Tool, icon:'↗', title:'Shock Index', category:'Emergency', desc:'HR dibagi SBP sebagai screening sederhana.' },
  { id:'tpm' as Tool, icon:'💧', title:'TPM Infus', category:'Fluid Therapy', desc:'Hitung tetes per menit dan mL/jam dari volume, waktu, dan drop factor.' },
  { id:'anion' as Tool, icon:'＋', title:'Anion Gap', category:'Metabolic', desc:'AG dan AG terkoreksi albumin.' },
  { id:'correctedNa' as Tool, icon:'Na', title:'Corrected Sodium', category:'Metabolic', desc:'Estimasi Na terkoreksi pada hiperglikemia.' },
  { id:'pedsFluid' as Tool, icon:'◒', title:'Pediatric Maintenance Fluid', category:'Pediatrics', desc:'Rumus Holliday–Segar / 4-2-1.' },
]

function Field({label,value,onChange,unit='',type='number',placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;unit?:string;type?:string;placeholder?:string}){return <label className="tool-field"><span>{label}</span><div className="input-wrap"><input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/><small>{unit}</small></div></label>}
function Result({value,label,note}:{value:string;label:string;note?:string}){return <div className="tool-result"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}

export default function ToolsPage(){
 const [active,setActive]=useState<Tool>('bmi'); const [query,setQuery]=useState('')
 const [weight,setWeight]=useState(''); const [height,setHeight]=useState(''); const [age,setAge]=useState(''); const [sex,setSex]=useState<'male'|'female'>('male'); const [scr,setScr]=useState(''); const [crclWeight,setCrclWeight]=useState('')
 const [gcsE,setGcsE]=useState('4'); const [gcsV,setGcsV]=useState('5'); const [gcsM,setGcsM]=useState('6'); const [sbp,setSbp]=useState(''); const [dbp,setDbp]=useState(''); const [hr,setHr]=useState('')
 const [na,setNa]=useState(''); const [cl,setCl]=useState(''); const [hco3,setHco3]=useState(''); const [albumin,setAlbumin]=useState('4'); const [glucose,setGlucose]=useState(''); const [fluidWeight,setFluidWeight]=useState('')
 const [tpmVolume,setTpmVolume]=useState(''); const [tpmTime,setTpmTime]=useState(''); const [dropFactor,setDropFactor]=useState('20')
 const filtered=useMemo(()=>toolCards.filter(t=>`${t.title} ${t.category} ${t.desc}`.toLowerCase().includes(query.toLowerCase())),[query])
 const bmi=weight&&height?Number(weight)/Math.pow(Number(height)/100,2):NaN
 const bsa=weight&&height?Math.sqrt((Number(weight)*Number(height))/3600):NaN
 const egfr=(()=>{const s=Number(scr),a=Number(age);if(!s||!a)return NaN;const k=sex==='female'?0.7:0.9;const alpha=sex==='female'?-0.241:-0.302;return 142*Math.pow(Math.min(s/k,1),alpha)*Math.pow(Math.max(s/k,1),-1.2)*Math.pow(0.9938,a)*(sex==='female'?1.012:1)})()
 const crcl=(()=>{const s=Number(scr),a=Number(age),w=Number(crclWeight);if(!s||!a||!w)return NaN;const base=((140-a)*w)/(72*s);return sex==='female'?base*0.85:base})()
 const map=sbp&&dbp?(Number(sbp)+2*Number(dbp))/3:NaN; const shock=hr&&sbp?Number(hr)/Number(sbp):NaN
 const ag=na&&cl&&hco3?Number(na)-Number(cl)-Number(hco3):NaN; const correctedAg=Number.isFinite(ag)&&albumin?ag+2.5*(4-Number(albumin)):NaN
 const correctedNa=na&&glucose?Number(na)+1.6*((Number(glucose)-100)/100):NaN
 const maintenance=(()=>{const w=Number(fluidWeight);if(!w)return NaN;return w<=10?w*4:w<=20?40+(w-10)*2:60+(w-20)})()
 const tpm=(()=>{const v=Number(tpmVolume),h=Number(tpmTime),f=Number(dropFactor);if(!v||!h||!f)return {gtt:NaN,mlhr:NaN};const mlhr=v/h;return {gtt:(v*f)/(h*60),mlhr}})()
 const activeTitle=toolCards.find(t=>t.id===active)?.title
 return <><ToolStyles/><div className="section tools-page"><div className="section-kicker">Clinical Tools</div><div className="tools-header"><div><h1>Clinical Tools</h1><p className="section-intro">Kalkulator klinis yang cepat, sederhana, dan transparan. Masukkan parameter pasien, lihat hasilnya, lalu verifikasi konteks klinis dan guideline.</p></div><div className="tools-count"><strong>{toolCards.length}</strong><span>tools aktif</span></div></div>
 <div className="tool-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari BMI, eGFR, TPM, GCS, anion gap..."/></div>
 <div className="tool-layout"><aside className="tool-sidebar"><div className="tool-side-label">ALL TOOLS</div>{filtered.map(t=><button key={t.id} onClick={()=>setActive(t.id)} className={`tool-nav ${active===t.id?'active':''}`}><span>{t.icon}</span><div><strong>{t.title}</strong><small>{t.category}</small></div></button>)}</aside>
 <main className="tool-workspace"><div className="tool-workspace-top"><div><span className="meta">CALCULATOR</span><h2>{activeTitle}</h2></div><span className="tool-status">Educational tool</span></div>
 {active==='bmi'&&<div className="tool-panel"><div className="tool-fields"><Field label="Berat badan" value={weight} onChange={setWeight} unit="kg"/><Field label="Tinggi badan" value={height} onChange={setHeight} unit="cm"/></div><div className="result-grid"><Result label="BMI" value={Number.isFinite(bmi)?bmi.toFixed(1):'—'} note={Number.isFinite(bmi)?bmi<18.5?'Underweight':bmi<25?'Normal':bmi<30?'Overweight':'Obesity':undefined}/><Result label="BSA" value={Number.isFinite(bsa)?`${bsa.toFixed(2)} m²`:'—'}/></div><p className="tool-note">Kategori BMI dapat berbeda menurut populasi dan konteks klinis. Gunakan cut-off yang sesuai dengan guideline/populasi pasien.</p></div>}
 {active==='bsa'&&<div className="tool-panel"><div className="tool-fields"><Field label="Berat badan" value={weight} onChange={setWeight} unit="kg"/><Field label="Tinggi badan" value={height} onChange={setHeight} unit="cm"/></div><Result label="Mosteller BSA" value={Number.isFinite(bsa)?`${bsa.toFixed(2)} m²`:'—'}/><p className="tool-note">BSA digunakan pada konteks tertentu seperti dosing berbasis luas permukaan tubuh. Pastikan obat memang direkomendasikan menggunakan BSA.</p></div>}
 {active==='egfr'&&<div className="tool-panel"><div className="tool-fields"><Field label="Serum creatinine" value={scr} onChange={setScr} unit="mg/dL"/><Field label="Usia" value={age} onChange={setAge} unit="tahun"/><label className="tool-field"><span>Jenis kelamin</span><select value={sex} onChange={e=>setSex(e.target.value as 'male'|'female')}><option value="male">Laki-laki</option><option value="female">Perempuan</option></select></label></div><Result label="eGFR CKD-EPI 2021" value={Number.isFinite(egfr)?`${egfr.toFixed(1)} mL/min/1.73 m²`:'—'}/><p className="tool-note">Estimasi berbasis creatinine, bukan pengukuran GFR langsung. Untuk drug dosing, jangan otomatis mengganti CrCl dengan eGFR tanpa mempertimbangkan rekomendasi obat.</p></div>}
 {active==='crcl'&&<div className="tool-panel"><div className="tool-fields"><Field label="Serum creatinine" value={scr} onChange={setScr} unit="mg/dL"/><Field label="Usia" value={age} onChange={setAge} unit="tahun"/><Field label="Berat badan" value={crclWeight} onChange={setCrclWeight} unit="kg"/><label className="tool-field"><span>Jenis kelamin</span><select value={sex} onChange={e=>setSex(e.target.value as 'male'|'female')}><option value="male">Laki-laki</option><option value="female">Perempuan</option></select></label></div><Result label="Cockcroft–Gault CrCl" value={Number.isFinite(crcl)?`${crcl.toFixed(1)} mL/min`:'—'}/><p className="tool-note">Pemilihan weight descriptor dapat mengubah CrCl. Pada obesitas, edema, atau ekstrem berat badan, ikuti referensi/protokol setempat.</p></div>}
 {active==='gcs'&&<div className="tool-panel"><div className="tool-fields"><label className="tool-field"><span>Eye opening</span><select value={gcsE} onChange={e=>setGcsE(e.target.value)}><option value="4">4 — Spontaneous</option><option value="3">3 — To voice</option><option value="2">2 — To pressure</option><option value="1">1 — None</option></select></label><label className="tool-field"><span>Verbal</span><select value={gcsV} onChange={e=>setGcsV(e.target.value)}><option value="5">5 — Oriented</option><option value="4">4 — Confused</option><option value="3">3 — Inappropriate words</option><option value="2">2 — Incomprehensible sounds</option><option value="1">1 — None</option></select></label><label className="tool-field"><span>Motor</span><select value={gcsM} onChange={e=>setGcsM(e.target.value)}><option value="6">6 — Obeys commands</option><option value="5">5 — Localizes</option><option value="4">4 — Normal flexion</option><option value="3">3 — Abnormal flexion</option><option value="2">2 — Extension</option><option value="1">1 — None</option></select></label></div><Result label="Total GCS" value={`${Number(gcsE)+Number(gcsV)+Number(gcsM)} / 15`}/><p className="tool-note">Dokumentasikan komponen E/V/M, bukan hanya total. Sedasi, paralisis, atau intubasi dapat membuat komponen tertentu tidak dapat dinilai.</p></div>}
 {active==='map'&&<div className="tool-panel"><div className="tool-fields"><Field label="Systolic BP" value={sbp} onChange={setSbp} unit="mmHg"/><Field label="Diastolic BP" value={dbp} onChange={setDbp} unit="mmHg"/></div><Result label="MAP" value={Number.isFinite(map)?`${map.toFixed(0)} mmHg`:'—'}/><p className="tool-note">MAP adalah estimasi sederhana dan tidak menggantikan penilaian perfusi organ secara keseluruhan.</p></div>}
 {active==='shock'&&<div className="tool-panel"><div className="tool-fields"><Field label="Heart rate" value={hr} onChange={setHr} unit="/min"/><Field label="Systolic BP" value={sbp} onChange={setSbp} unit="mmHg"/></div><Result label="Shock Index" value={Number.isFinite(shock)?shock.toFixed(2):'—'}/><p className="tool-note">Shock Index adalah screening adjunctive, bukan alat diagnosis tunggal.</p></div>}
 {active==='tpm'&&<div className="tool-panel"><div className="tool-fields"><Field label="Volume cairan" value={tpmVolume} onChange={setTpmVolume} unit="mL" placeholder="500"/><Field label="Waktu pemberian" value={tpmTime} onChange={setTpmTime} unit="jam" placeholder="4"/><label className="tool-field"><span>Drop factor infus</span><select value={dropFactor} onChange={e=>setDropFactor(e.target.value)}><option value="10">Macrodrip — 10 gtt/mL</option><option value="15">Macrodrip — 15 gtt/mL</option><option value="20">Macrodrip — 20 gtt/mL</option><option value="60">Microdrip — 60 gtt/mL</option></select></label></div><div className="result-grid"><Result label="TPM / tetes per menit" value={Number.isFinite(tpm.gtt)?`${Math.round(tpm.gtt)} tetes/menit`:'—'} note="Bulatkan ke tetes/menit terdekat sesuai kemampuan pengaturan infus."/><Result label="Kecepatan cairan" value={Number.isFinite(tpm.mlhr)?`${tpm.mlhr.toFixed(1)} mL/jam`:'—'}/></div><p className="tool-note"><b>Rumus:</b> TPM = volume (mL) × drop factor (gtt/mL) ÷ waktu (menit). Waktu dalam kalkulator dimasukkan dalam jam dan otomatis dikonversi ke menit. Pastikan drop factor sesuai kemasan infus set yang digunakan.</p></div>}
 {active==='anion'&&<div className="tool-panel"><div className="tool-fields"><Field label="Na⁺" value={na} onChange={setNa} unit="mmol/L"/><Field label="Cl⁻" value={cl} onChange={setCl} unit="mmol/L"/><Field label="HCO₃⁻" value={hco3} onChange={setHco3} unit="mmol/L"/><Field label="Albumin" value={albumin} onChange={setAlbumin} unit="g/dL"/></div><div className="result-grid"><Result label="Anion Gap" value={Number.isFinite(ag)?`${ag.toFixed(1)} mmol/L`:'—'}/><Result label="AG corrected for albumin" value={Number.isFinite(correctedAg)?`${correctedAg.toFixed(1)} mmol/L`:'—'}/></div><p className="tool-note">Formula: AG = Na − (Cl + HCO₃). Koreksi albumin menggunakan pendekatan 2.5 × (4 − albumin).</p></div>}
 {active==='correctedNa'&&<div className="tool-panel"><div className="tool-fields"><Field label="Serum sodium" value={na} onChange={setNa} unit="mmol/L"/><Field label="Glucose" value={glucose} onChange={setGlucose} unit="mg/dL"/></div><Result label="Corrected Na⁺" value={Number.isFinite(correctedNa)?`${correctedNa.toFixed(1)} mmol/L`:'—'}/><p className="tool-note">Menggunakan faktor koreksi 1.6 mmol/L untuk setiap kenaikan glukosa 100 mg/dL di atas 100 mg/dL. Beberapa referensi menggunakan faktor berbeda pada hiperglikemia berat.</p></div>}
 {active==='pedsFluid'&&<div className="tool-panel"><div className="tool-fields"><Field label="Berat badan anak" value={fluidWeight} onChange={setFluidWeight} unit="kg"/></div><div className="result-grid"><Result label="Maintenance / jam" value={Number.isFinite(maintenance)?`${maintenance.toFixed(1)} mL/jam`:'—'}/><Result label="Maintenance / 24 jam" value={Number.isFinite(maintenance)?`${(maintenance*24).toFixed(0)} mL/hari`:'—'}/></div><p className="tool-note">Holliday–Segar 4-2-1. Untuk pasien sakit kritis, gangguan ginjal/jantung, elektrolit abnormal, atau kebutuhan khusus, maintenance harus dimodifikasi berdasarkan kondisi klinis dan monitoring.</p></div>}
 <div className="tool-disclaimer"><strong>Clinical safety note</strong><span>Tool ini untuk edukasi dan clinical decision support. Hasil kalkulator bukan diagnosis atau instruksi terapi otomatis. Verifikasi input, satuan, formula, kontraindikasi, guideline terbaru, serta protokol lokal sebelum digunakan pada pasien nyata.</span></div>
 </main></div>
 <FluidGuide/>
 </div></>
}
