export type Category =
  | 'Antibiotics' | 'Pediatrics' | 'Emergency' | 'Respiratory' | 'Cardiovascular'
  | 'Neurology' | 'Endocrine' | 'GI' | 'Dermatology' | 'Infectious'
  | 'Pain' | 'OBGYN' | 'Renal' | 'Psychiatry' | 'Urology' | 'Rheumatology'

export type Population = 'Adult' | 'Pediatric' | 'Neonate' | 'Adult + Pediatric' | 'Pregnancy'
export type DoseRule =
  | { kind:'fixed'; amount:number; unit:string; frequency:string; duration?:string; maxDaily?:number }
  | { kind:'mgkg'; amount:number; unit:string; frequency:string; duration?:string; maxDose?:number; maxDaily?:number }
  | { kind:'mgkgday'; amount:number; unit:string; frequency:string; duration?:string; maxDaily?:number }
  | { kind:'bsa'; amount:number; unit:string; frequency:string; duration?:string; maxDose?:number; maxDaily?:number }
  | { kind:'protocol'; amount:number; unit:string; frequency:string; duration?:string }

export type RenalBand = { label:string; min?:number; max?:number; adjustment:string }
export type DrugRegimen = {
  id:string; drug:string; aliases?:string[]; indication:string; category:Category; population:Population; route:string;
  rule:DoseRule; renal?:RenalBand[]; hepatic?:string; pregnancy?:string; warnings?:string[]; notes?:string;
  formulation?:string; status:'Guideline-verified'|'Reference-based — verify'; source:string; reviewed:string
}

const r=(x:Omit<DrugRegimen,'reviewed'>):DrugRegimen=>({...x,reviewed:'2026-09'})
const fixed=(amount:number,unit:string,frequency:string,duration?:string,maxDaily?:number):DoseRule=>({kind:'fixed',amount,unit,frequency,duration,maxDaily})
const mgkg=(amount:number,unit:string,frequency:string,duration?:string,maxDose?:number,maxDaily?:number):DoseRule=>({kind:'mgkg',amount,unit,frequency,duration,maxDose,maxDaily})
const mgkgday=(amount:number,unit:string,frequency:string,duration?:string,maxDaily?:number):DoseRule=>({kind:'mgkgday',amount,unit,frequency,duration,maxDaily})

export const DRUG_DB:DrugRegimen[] = [
/* ANALGESIA / GENERAL */
 r({id:'paracetamol-adult',drug:'Paracetamol',indication:'Nyeri / demam',category:'Pain',population:'Adult',route:'PO',rule:fixed(500,'mg','3–4×/hari bila perlu',undefined,4000),warnings:['Pertimbangkan batas lebih rendah pada penyakit hati, malnutrisi, alkohol berlebih, atau penggunaan kronis.'],status:'Guideline-verified',source:'WHO / standard adult analgesic dosing; kompilasi pengguna'}),
 r({id:'paracetamol-child',drug:'Paracetamol',indication:'Nyeri / demam — anak',category:'Pediatrics',population:'Pediatric',route:'PO',rule:mgkg(15,'mg/kg/dosis','setiap 4–6 jam bila perlu',undefined,1000,60),notes:'Gunakan berat badan aktual dan sediaan yang tepat.',status:'Guideline-verified',source:'WHO pediatric guidance; kompilasi pengguna'}),
 r({id:'ibuprofen-adult',drug:'Ibuprofen',indication:'Nyeri / inflamasi',category:'Pain',population:'Adult',route:'PO',rule:fixed(400,'mg','3×/hari bila perlu',undefined,1200),warnings:['Hindari/waspadai CKD, dehidrasi, ulkus/GI bleed, gagal jantung, antikoagulan, dan kehamilan trimester lanjut.'],status:'Guideline-verified',source:'Standard NSAID dosing; kompilasi pengguna'}),
 r({id:'ibuprofen-child',drug:'Ibuprofen',indication:'Nyeri / demam — anak',category:'Pediatrics',population:'Pediatric',route:'PO',rule:mgkg(10,'mg/kg/dosis','setiap 6–8 jam bila perlu',undefined,400,40),warnings:['Hindari pada dehidrasi berat dan penyakit ginjal; cek batas usia produk.'],status:'Guideline-verified',source:'WHO pediatric guidance'}),
 r({id:'diclofenac',drug:'Diclofenac',indication:'Nyeri muskuloskeletal akut',category:'Pain',population:'Adult',route:'PO',rule:fixed(50,'mg','2–3×/hari setelah makan',undefined,150),warnings:['Gunakan dosis efektif terendah dan durasi sesingkat mungkin; risiko GI, renal, dan kardiovaskular.'],status:'Guideline-verified',source:'Standard NSAID dosing'}),
 r({id:'ketorolac',drug:'Ketorolac',indication:'Nyeri akut sedang–berat',category:'Pain',population:'Adult',route:'IV/IM',rule:fixed(15,'mg','setiap 6 jam bila perlu',undefined,60),warnings:['Durasi sistemik harus singkat; hindari pada GI bleeding, renal impairment signifikan, dan kombinasi NSAID.'],status:'Reference-based — verify',source:'FDA/label-based dosing; kompilasi pengguna'}),
 r({id:'morphine',drug:'Morphine',indication:'Nyeri akut berat',category:'Pain',population:'Adult',route:'IV titrasi',rule:fixed(2,'mg','titrasi tiap 5–10 menit sesuai respons',undefined,30),warnings:['Monitor airway, respiratory rate, sedation, BP; siapkan nalokson bila risiko depresi napas.'],status:'Reference-based — verify',source:'Standard emergency opioid protocols'}),
/* ANTIBIOTICS */
 r({id:'amoxicillin-adult',drug:'Amoxicillin',indication:'Infeksi bakteri sensitif — dewasa',category:'Antibiotics',population:'Adult',route:'PO',rule:fixed(500,'mg','3×/hari'),status:'Guideline-verified',source:'WHO AWaRe antibiotic guidance'}),
 r({id:'amoxicillin-cap',drug:'Amoxicillin',indication:'Community-acquired pneumonia — rawat jalan',category:'Antibiotics',population:'Adult',route:'PO',rule:fixed(1000,'mg','3×/hari', '5 hari'),status:'Guideline-verified',source:'ATS/IDSA CAP guidance + WHO AWaRe'}),
 r({id:'amoxicillin-child',drug:'Amoxicillin',indication:'CAP / otitis media — anak',category:'Pediatrics',population:'Pediatric',route:'PO',rule:mgkgday(80,'mg/kg/hari','dibagi 2–3 dosis','5 hari',3000),notes:'Indikasi dan durasi harus mengikuti guideline penyakit dan usia.',status:'Guideline-verified',source:'WHO 2024 pneumonia/diarrhoea guidance; IDSA/PIDS 2026 CAP'}),
 r({id:'amoxclav-adult',drug:'Amoxicillin/clavulanate',indication:'Infeksi respirasi / odontogenik tertentu',category:'Antibiotics',population:'Adult',route:'PO',rule:fixed(875,'mg amoxicillin component','2×/hari','5–7 hari'),warnings:['Pastikan kekuatan sediaan; dosis harus dinyatakan berdasarkan komponen amoxicillin.'],status:'Guideline-verified',source:'NICE / WHO AWaRe'}),
 r({id:'amoxclav-child',drug:'Amoxicillin/clavulanate',indication:'Infeksi bakteri tertentu — anak',category:'Pediatrics',population:'Pediatric',route:'PO',rule:mgkgday(45,'mg/kg/hari amoxicillin component','dibagi 2 dosis','5–7 hari',4000),warnings:['Gunakan sediaan pediatric yang sesuai rasio amoxicillin:clavulanate.'],status:'Guideline-verified',source:'WHO AWaRe / pediatric antimicrobial guidance'}),
 r({id:'penicillin-v',drug:'Phenoxymethylpenicillin',indication:'Streptococcal pharyngitis',category:'Antibiotics',population:'Adult',route:'PO',rule:fixed(500,'mg','2×/hari','10 hari'),status:'Guideline-verified',source:'CDC Group A Streptococcal Pharyngitis guidance'}),
 r({id:'benzathine-penicillin',drug:'Benzathine benzylpenicillin',indication:'Sifilis primer/sekunder/early latent',category:'Infectious',population:'Adult',route:'IM',rule:fixed(2400000,'IU','dosis tunggal'),warnings:['Pastikan sediaan benzathine penicillin; bukan IV.'],status:'Guideline-verified',source:'CDC STI Treatment Guidelines / WHO STI guidance'}),
 r({id:'ceftriaxone-gonorrhea',drug:'Ceftriaxone',indication:'Gonore tidak terkomplikasi',category:'Infectious',population:'Adult',route:'IM',rule:fixed(500,'mg','dosis tunggal'),notes:'BB ≥150 kg: 1 g. Jika klamidia belum dieksklusi, gunakan regimen klamidia yang sesuai.',status:'Guideline-verified',source:'CDC STI Treatment Guidelines'}),
 r({id:'ceftriaxone-cap',drug:'Ceftriaxone',indication:'CAP dewasa rawat inap',category:'Antibiotics',population:'Adult',route:'IV',rule:fixed(1000,'mg','1×/hari'),notes:'Biasanya dikombinasikan dengan makrolida pada CAP rawat inap non-berat.',status:'Guideline-verified',source:'ATS/IDSA CAP guidance'}),
 r({id:'ceftriaxone-ped',drug:'Ceftriaxone',indication:'Infeksi bakteri berat — anak',category:'Pediatrics',population:'Pediatric',route:'IV/IM',rule:mgkg(50,'mg/kg/dosis','1×/hari',undefined,2000),status:'Guideline-verified',source:'WHO pediatric serious bacterial infection guidance'}),
 r({id:'cefalexin-uti',drug:'Cefalexin',indication:'ISK bawah pada kehamilan',category:'OBGYN',population:'Pregnancy',route:'PO',rule:fixed(500,'mg','2–3×/hari','7 hari'),status:'Guideline-verified',source:'NICE NG109'}),
 r({id:'doxy-chlamydia',drug:'Doxycycline',indication:'Chlamydia trachomatis',category:'Infectious',population:'Adult',route:'PO',rule:fixed(100,'mg','2×/hari','7 hari'),warnings:['Hindari pada kehamilan dan perhatikan kelompok usia/kontraindikasi produk.'],status:'Guideline-verified',source:'CDC STI Treatment Guidelines'}),
 r({id:'doxy-lepto',drug:'Doxycycline',indication:'Leptospirosis ringan — dewasa',category:'Infectious',population:'Adult',route:'PO',rule:fixed(100,'mg','2×/hari','7 hari'),status:'Guideline-verified',source:'CDC/WHO leptospirosis guidance; kompilasi pengguna'}),
 r({id:'azithro-chest',drug:'Azithromycin',indication:'Respiratory bacterial infection / CAP selected cases',category:'Respiratory',population:'Adult',route:'PO',rule:fixed(500,'mg','hari 1, lalu 250 mg/hari hari 2–5'),warnings:['Macrolide resistance dan QT prolongation harus dipertimbangkan.'],status:'Guideline-verified',source:'ATS/IDSA CAP guidance'}),
 r({id:'azithro-ped',drug:'Azithromycin',indication:'Infeksi respirasi tertentu — anak',category:'Pediatrics',population:'Pediatric',route:'PO',rule:mgkg(10,'mg/kg','1×/hari','3 hari',500),status:'Guideline-verified',source:'WHO pediatric antimicrobial guidance'}),
 r({id:'doxy-malaria',drug:'Doxycycline',indication:'Profilaksis malaria',category:'Infectious',population:'Adult',route:'PO',rule:fixed(100,'mg','1×/hari'),warnings:['Mulai sebelum perjalanan sesuai regimen profilaksis dan lanjutkan setelah meninggalkan area risiko sesuai guideline.'],status:'Guideline-verified',source:'CDC Yellow Book / malaria prevention guidance'}),
 r({id:'nitrofurantoin-uti',drug:'Nitrofurantoin MR',indication:'ISK bawah non-komplikasi',category:'Antibiotics',population:'Adult',route:'PO',rule:fixed(100,'mg','2×/hari','3 hari'),renal:[{label:'eGFR ≥45',min:45,adjustment:'Regimen standar dapat digunakan bila sesuai indikasi.'},{label:'eGFR <45',max:45,adjustment:'Tidak rutin digunakan; ikuti guideline lokal dan pertimbangkan alternatif.'}],warnings:['Tidak untuk pielonefritis atau infeksi sistemik.'],status:'Guideline-verified',source:'NICE NG109'}),
 r({id:'fosfomycin-uti',drug:'Fosfomycin trometamol',indication:'ISK bawah non-komplikasi pada perempuan',category:'Antibiotics',population:'Adult',route:'PO',rule:fixed(3000,'mg','dosis tunggal'),status:'Guideline-verified',source:'EAU/NICE uncomplicated UTI guidance'}),
 r({id:'metronidazole-anaerobe',drug:'Metronidazole',indication:'Infeksi anaerob / intra-abdominal selected',category:'Antibiotics',population:'Adult',route:'PO/IV',rule:fixed(500,'mg','3×/hari'),warnings:['Sesuaikan indikasi, durasi, dan kombinasi antibiotik dengan sumber infeksi.'],status:'Guideline-verified',source:'WHO AWaRe / IDSA intra-abdominal infection guidance'}),
 r({id:'clindamycin',drug:'Clindamycin',indication:'Infeksi Gram-positive/anaerob selected',category:'Antibiotics',population:'Adult',route:'PO/IV',rule:fixed(300,'mg','3×/hari PO; IV sesuai protokol'),warnings:['Risiko C. difficile; gunakan hanya bila indikasi tepat.'],status:'Guideline-verified',source:'WHO AWaRe'}),
 r({id:'cipro-pyelonephritis',drug:'Ciprofloxacin',indication:'Pielonefritis/ISK terpilih berdasarkan sensitivitas',category:'Antibiotics',population:'Adult',route:'PO',rule:fixed(500,'mg','2×/hari','7 hari'),warnings:['Gunakan hanya bila guideline lokal dan resistensi mendukung; risiko tendon, QT, CNS, aortic events.'],status:'Guideline-verified',source:'EAU Urological Infections guidance'}),
 r({id:'piptazo-severe',drug:'Piperacillin/tazobactam',indication:'Infeksi berat Gram-negative/Pseudomonas selected',category:'Antibiotics',population:'Adult',route:'IV',rule:fixed(4500,'mg','setiap 6–8 jam extended/standard infusion sesuai protokol'),renal:[{label:'Renal impairment',adjustment:'Gunakan tabel penyesuaian resmi produk/protokol rumah sakit berdasarkan CrCl.'}],warnings:['Antibiotic stewardship: kultur dan de-eskalasi bila memungkinkan.'],status:'Guideline-verified',source:'IDSA AMR Guidance 2026; product labeling'}),
 r({id:'cefepime',drug:'Cefepime',indication:'Infeksi Gram-negative/Pseudomonas berat selected',category:'Antibiotics',population:'Adult',route:'IV',rule:fixed(2000,'mg','setiap 8–12 jam sesuai indikasi'),renal:[{label:'CrCl rendah',adjustment:'WAJIB renal adjustment berdasarkan CrCl dan indikasi.'}],warnings:['Neurotoxicity risk pada renal impairment; pastikan penyesuaian dosis.'],status:'Guideline-verified',source:'IDSA AMR Guidance 2026; product labeling'}),
 r({id:'meropenem',drug:'Meropenem',indication:'Infeksi berat / ESBL selected',category:'Antibiotics',population:'Adult',route:'IV',rule:fixed(1000,'mg','setiap 8 jam'),renal:[{label:'CrCl rendah',adjustment:'Sesuaikan berdasarkan CrCl sesuai label/protokol.'}],warnings:['Reserve broad-spectrum use for appropriate indications; review cultures daily.'],status:'Guideline-verified',source:'IDSA AMR Guidance 2026; product labeling'}),
 r({id:'vancomycin',drug:'Vancomycin',indication:'Serious Gram-positive/MRSA infection',category:'Antibiotics',population:'Adult',route:'IV',rule:mgkg(15,'mg/kg/dosis','interval berdasarkan AUC/renal function'),renal:[{label:'Renal impairment',adjustment:'Individualize using AUC-guided monitoring and renal function.'}],warnings:['Therapeutic drug monitoring diperlukan pada serious MRSA infection.'],status:'Guideline-verified',source:'2020 ASHP/IDSA/PIDS/SIDP vancomycin monitoring guidance'}),
 r({id:'linezolid',drug:'Linezolid',indication:'MRSA pneumonia / resistant Gram-positive selected',category:'Antibiotics',population:'Adult',route:'PO/IV',rule:fixed(600,'mg','2×/hari','sesuai durasi infeksi'),warnings:['Monitor CBC; interaksi serotonergik dan neuropati pada penggunaan lama.'],status:'Guideline-verified',source:'IDSA MRSA/AMR guidance'}),
/* RESPIRATORY */
 r({id:'salbutamol-neb',drug:'Salbutamol',indication:'Eksaserbasi asma/COPD',category:'Respiratory',population:'Adult',route:'Nebulizer',rule:fixed(2.5,'mg','dapat diulang sesuai respons/protokol'),warnings:['Dosis dan interval mengikuti usia, berat eksaserbasi, dan protokol fasilitas.'],status:'Guideline-verified',source:'GINA 2026 / GOLD strategy'}),
 r({id:'salbutamol-child',drug:'Salbutamol',indication:'Bronkospasme akut — anak',category:'Pediatrics',population:'Pediatric',route:'Nebulizer',rule:fixed(2.5,'mg','sesuai usia/protokol'),warnings:['Untuk anak kecil, gunakan dosis perangkat/formulasi yang sesuai.'],status:'Guideline-verified',source:'GINA 2026 pediatric asthma'}),
 r({id:'budesonide-formoterol-mart',drug:'Budesonide-formoterol',indication:'Asma — reliever/MART',category:'Respiratory',population:'Adult + Pediatric',route:'Inhalasi',rule:fixed(1,'inhalasi','bila perlu / maintenance sesuai regimen'),warnings:['Batas maksimum harian bergantung usia dan kekuatan inhaler; cek label spesifik.'],status:'Guideline-verified',source:'GINA Strategy Report 2026'}),
 r({id:'prednisone-asthma',drug:'Prednisone/Prednisolone',indication:'Eksaserbasi asma dewasa',category:'Respiratory',population:'Adult',route:'PO',rule:fixed(40,'mg','1×/hari','5–7 hari'),status:'Guideline-verified',source:'GINA Strategy Report 2026'}),
 r({id:'prednisolone-asthma-child',drug:'Prednisolone',indication:'Eksaserbasi asma — anak',category:'Pediatrics',population:'Pediatric',route:'PO',rule:mgkg(1,'mg/kg/hari','1×/hari','3–5 hari',40),status:'Guideline-verified',source:'GINA Strategy Report 2026'}),
 r({id:'prednisone-copd',drug:'Prednisone',indication:'Eksaserbasi COPD',category:'Respiratory',population:'Adult',route:'PO',rule:fixed(40,'mg','1×/hari','5 hari'),status:'Guideline-verified',source:'GOLD strategy report'}),
 r({id:'ipratropium',drug:'Ipratropium',indication:'Bronkospasme akut',category:'Respiratory',population:'Adult',route:'Nebulizer',rule:fixed(0.5,'mg','setiap 20 menit ×3 pada fase awal, lalu sesuai respons'),status:'Guideline-verified',source:'GINA 2026 / emergency asthma protocols'}),
 r({id:'theophylline-no',drug:'Theophylline',indication:'—',category:'Respiratory',population:'Adult',route:'PO',rule:{kind:'protocol',amount:0,unit:'',frequency:'Tidak direkomendasikan sebagai routine first-line controller'},warnings:['Tidak dipakai sebagai routine asthma controller modern karena therapeutic window sempit dan interaksi banyak.'],status:'Guideline-verified',source:'GINA Strategy Report 2026'}),
/* CARDIOVASCULAR */
 r({id:'amlodipine',drug:'Amlodipine',indication:'Hipertensi',category:'Cardiovascular',population:'Adult',route:'PO',rule:fixed(5,'mg','1×/hari'),notes:'Titrasi berdasarkan tekanan darah dan tolerabilitas.',status:'Guideline-verified',source:'NICE NG136'}),
 r({id:'lisinopril',drug:'Lisinopril',indication:'Hipertensi / heart failure selected',category:'Cardiovascular',population:'Adult',route:'PO',rule:fixed(10,'mg','1×/hari awal; titrasi'),warnings:['Monitor creatinine dan potassium; kontraindikasi pada kehamilan.'],status:'Guideline-verified',source:'NICE hypertension/heart failure guidance'}),
 r({id:'losartan',drug:'Losartan',indication:'Hipertensi',category:'Cardiovascular',population:'Adult',route:'PO',rule:fixed(50,'mg','1×/hari'),warnings:['Monitor renal function/K+; kontraindikasi pada kehamilan.'],status:'Guideline-verified',source:'NICE NG136'}),
 r({id:'bisoprolol',drug:'Bisoprolol',indication:'Heart failure / rate control selected',category:'Cardiovascular',population:'Adult',route:'PO',rule:fixed(1.25,'mg','1×/hari awal; titrasi'),warnings:['Titrasi perlahan; monitor HR/BP dan decompensation.'],status:'Guideline-verified',source:'ESC heart failure guidance'}),
 r({id:'furosemide-heart-failure',drug:'Furosemide',indication:'Congestion pada heart failure',category:'Cardiovascular',population:'Adult',route:'PO/IV',rule:fixed(20,'mg','1×/hari awal; titrasi sesuai congestion'),warnings:['Monitor weight, urine output, electrolytes, renal function.'],status:'Guideline-verified',source:'ESC heart failure guidance'}),
 r({id:'spironolactone-hf',drug:'Spironolactone',indication:'HFrEF selected',category:'Cardiovascular',population:'Adult',route:'PO',rule:fixed(25,'mg','1×/hari'),warnings:['Monitor K+ dan renal function; hindari/adjust bila hyperkalemia atau renal impairment berat.'],status:'Guideline-verified',source:'ESC heart failure guidance'}),
 r({id:'aspirin-acs',drug:'Aspirin',indication:'ACS — loading',category:'Cardiovascular',population:'Adult',route:'PO',rule:fixed(300,'mg','loading, kunyah'),warnings:['Pastikan tidak ada active major bleeding/true allergy.'],status:'Guideline-verified',source:'ESC ACS guidance'}),
 r({id:'clopidogrel-acs',drug:'Clopidogrel',indication:'ACS — P2Y12 selected',category:'Cardiovascular',population:'Adult',route:'PO',rule:fixed(300,'mg','loading pada strategi yang sesuai'),notes:'Loading dose bergantung strategi PCI/fibrinolysis dan antiplatelet plan.',status:'Guideline-verified',source:'ESC ACS guidance'}),
 r({id:'nitroglycerin',drug:'Nitroglycerin',indication:'Angina / ACS selected',category:'Cardiovascular',population:'Adult',route:'SL',rule:fixed(0.4,'mg','1 dose tiap 5 menit bila perlu, maksimal 3 dose'),warnings:['Jangan gunakan dengan PDE-5 inhibitor atau pada kondisi preload-dependent tertentu.'],status:'Guideline-verified',source:'AHA/ACC ACS and chest pain guidance'}),
 r({id:'atorvastatin',drug:'Atorvastatin',indication:'ASCVD / dyslipidemia',category:'Cardiovascular',population:'Adult',route:'PO',rule:fixed(40,'mg','1×/hari'),notes:'Intensitas terapi disesuaikan risiko ASCVD.',status:'Guideline-verified',source:'ACC/AHA lipid guidance'}),
/* ENDOCRINE */
 r({id:'metformin',drug:'Metformin',indication:'Type 2 diabetes',category:'Endocrine',population:'Adult',route:'PO',rule:fixed(500,'mg','1×/hari awal; titrasi bertahap'),renal:[{label:'eGFR ≥45',min:45,adjustment:'Dapat digunakan; monitor renal function.'},{label:'eGFR 30–44',min:30,max:44,adjustment:'Jangan memulai rutin; bila sudah digunakan, reassess dose/benefit.'},{label:'eGFR <30',max:30,adjustment:'Kontraindikasi.'}],warnings:['Pilihan obat DM 2026 harus mempertimbangkan CKD, ASCVD/HF, weight, hypoglycemia, cost, dan preference.'],status:'Guideline-verified',source:'ADA Standards of Care 2026'}),
 r({id:'empagliflozin',drug:'Empagliflozin',indication:'T2D dengan cardiorenal benefit selected',category:'Endocrine',population:'Adult',route:'PO',rule:fixed(10,'mg','1×/hari'),warnings:['Assess eGFR, volume status, genital infection risk; hold in selected acute illness/fasting.'],status:'Guideline-verified',source:'ADA Standards of Care 2026'}),
 r({id:'dapagliflozin',drug:'Dapagliflozin',indication:'T2D / CKD / HF selected',category:'Endocrine',population:'Adult',route:'PO',rule:fixed(10,'mg','1×/hari'),warnings:['Indikasi dan eGFR threshold berbeda menurut tujuan terapi dan label lokal.'],status:'Guideline-verified',source:'ADA Standards of Care 2026; KDIGO CKD guidance'}),
 r({id:'glimepiride',drug:'Glimepiride',indication:'T2D — sulfonylurea selected',category:'Endocrine',population:'Adult',route:'PO',rule:fixed(1,'mg','1×/hari awal; titrasi'),warnings:['Hypoglycemia risk; ekstra hati-hati lansia/renal/hepatic impairment.'],status:'Guideline-verified',source:'ADA Standards of Care 2026'}),
 r({id:'insulin-glargine',drug:'Insulin glargine',indication:'Basal insulin initiation in diabetes',category:'Endocrine',population:'Adult',route:'SC',rule:fixed(10,'units','1×/hari awal; titrasi 2–4 unit tiap 3 hari sesuai glucose'),warnings:['Individualize; edukasi hypoglycemia dan injection technique.'],status:'Guideline-verified',source:'ADA Standards of Care 2026'}),
 r({id:'insulin-dka',drug:'Regular insulin',indication:'DKA — IV protocol',category:'Emergency',population:'Adult',route:'IV infusion',rule:fixed(0.1,'unit/kg/hour','continuous after potassium assessment'),warnings:['Gunakan DKA protocol lengkap: potassium, fluids, glucose, anion gap/ketones; jangan berdiri sendiri.'],status:'Guideline-verified',source:'ADA Standards of Care 2026 hyperglycemic crises'}),
 r({id:'methimazole',drug:'Methimazole',indication:'Hyperthyroidism',category:'Endocrine',population:'Adult',route:'PO',rule:fixed(10,'mg','1–2×/hari awal; titrasi menurut severity'),warnings:['Agranulocytosis/hepatotoxicity counseling; pregnancy requires trimester-specific strategy.'],status:'Guideline-verified',source:'ATA hyperthyroidism guidance'}),
 r({id:'hydrocortisone-adrenal',drug:'Hydrocortisone',indication:'Adrenal crisis',category:'Emergency',population:'Adult',route:'IV',rule:fixed(100,'mg','bolus segera, lalu 200 mg/24 h infusion or divided doses'),warnings:['Emergency: do not delay steroid for confirmatory testing when adrenal crisis suspected.'],status:'Guideline-verified',source:'Endocrine Society adrenal insufficiency guidance'}),
/* GI */
 r({id:'omeprazole',drug:'Omeprazole',indication:'GERD / acid-related disease',category:'GI',population:'Adult',route:'PO',rule:fixed(20,'mg','1×/hari sebelum makan','4–8 minggu'),status:'Guideline-verified',source:'ACG GERD guidance'}),
 r({id:'omeprazole-ugi',drug:'Omeprazole',indication:'Upper GI bleeding — selected inpatient protocol',category:'GI',population:'Adult',route:'IV',rule:fixed(80,'mg','bolus then 8 mg/hour infusion for 72 h'),warnings:['High-dose IV PPI is post-endoscopic high-risk ulcer protocol; not routine dyspepsia treatment.'],status:'Guideline-verified',source:'ACG Upper GI and Ulcer Bleeding guidance'}),
 r({id:'ondansetron',drug:'Ondansetron',indication:'Nausea/vomiting',category:'GI',population:'Adult',route:'PO/IV',rule:fixed(4,'mg','setiap 8–12 jam bila perlu'),warnings:['QT prolongation risk; adjust/avoid in selected patients.'],status:'Guideline-verified',source:'Product labeling / standard antiemetic guidance'}),
 r({id:'oral-rehydration',drug:'Oral Rehydration Solution',indication:'Acute diarrhoea dehydration',category:'GI',population:'Adult + Pediatric',route:'PO',rule:fixed(200,'mL','setiap BAB cair pada anak; adult according to thirst/losses'),notes:'Gunakan ORS low-osmolarity dan nilai derajat dehidrasi.',status:'Guideline-verified',source:'WHO diarrhoea guidance'}),
 r({id:'zinc-child',drug:'Zinc',indication:'Acute diarrhoea — child',category:'Pediatrics',population:'Pediatric',route:'PO',rule:fixed(20,'mg elemental','1×/hari','10–14 hari'),notes:'Bayi muda menggunakan dosis lebih rendah sesuai guideline usia.',status:'Guideline-verified',source:'WHO diarrhoea guidance'}),
 r({id:'loperamide',drug:'Loperamide',indication:'Acute non-bloody diarrhoea — adult selected',category:'GI',population:'Adult',route:'PO',rule:fixed(4,'mg','initial, then 2 mg after loose stool',undefined,16),warnings:['Jangan gunakan bila bloody diarrhoea, high fever, suspected invasive infection, or ileus.'],status:'Guideline-verified',source:'WHO/standard symptomatic diarrhoea guidance'}),
/* NEURO */
 r({id:'sumatriptan',drug:'Sumatriptan',indication:'Acute migraine',category:'Neurology',population:'Adult',route:'PO',rule:fixed(50,'mg','single dose; may repeat after 2 h if needed',undefined,200),warnings:['Contraindications include certain ischemic vascular diseases; avoid medication-overuse pattern.'],status:'Guideline-verified',source:'AHS migraine guidance / product labeling'}),
 r({id:'carbamazepine-tn',drug:'Carbamazepine',indication:'Trigeminal neuralgia',category:'Neurology',population:'Adult',route:'PO',rule:fixed(100,'mg','2×/hari awal; titrasi'),warnings:['Monitor CBC, sodium, liver function; many drug interactions.'],status:'Guideline-verified',source:'AAN/EFNS trigeminal neuralgia guidance'}),
 r({id:'levetiracetam',drug:'Levetiracetam',indication:'Focal seizures — adjunct/monotherapy selected',category:'Neurology',population:'Adult',route:'PO/IV',rule:fixed(500,'mg','2×/hari awal; titrasi'),renal:[{label:'Renal impairment',adjustment:'Dose adjustment required according to CrCl.'}],status:'Guideline-verified',source:'AAN/ILAE seizure treatment guidance; product label'}),
 r({id:'diazepam-seizure',drug:'Diazepam',indication:'Prolonged convulsive seizure — emergency',category:'Emergency',population:'Adult',route:'IV/rectal',rule:mgkg(0.15,'mg/kg/dose','single emergency dose; repeat per protocol',undefined,10),warnings:['Airway and respiratory monitoring mandatory; follow status epilepticus protocol.'],status:'Guideline-verified',source:'AES/ILAE status epilepticus guidance'}),
 r({id:'midazolam-seizure',drug:'Midazolam',indication:'Status epilepticus — emergency',category:'Emergency',population:'Adult',route:'IM/buccal/IN',rule:fixed(10,'mg','single emergency dose for appropriate adult formulation'),warnings:['Dose depends on route and patient size; follow local status epilepticus protocol.'],status:'Guideline-verified',source:'AES/ILAE status epilepticus guidance'}),
 r({id:'levodopa-carbidopa',drug:'Levodopa/carbidopa',indication:'Parkinson disease',category:'Neurology',population:'Adult',route:'PO',rule:fixed(100,'mg levodopa component','3×/hari awal; titrasi'),warnings:['Individualize and monitor dyskinesia, hallucination, orthostasis.'],status:'Reference-based — verify',source:'Movement disorder standard guidance'}),
/* PSYCHIATRY */
 r({id:'sertraline',drug:'Sertraline',indication:'Depression / anxiety disorders',category:'Psychiatry',population:'Adult',route:'PO',rule:fixed(50,'mg','1×/hari; titrasi'),warnings:['Assess suicidality, serotonin syndrome risk, and bipolarity before antidepressant monotherapy.'],status:'Guideline-verified',source:'NICE depression/anxiety guidance'}),
 r({id:'fluoxetine',drug:'Fluoxetine',indication:'Depression / selected anxiety disorders',category:'Psychiatry',population:'Adult',route:'PO',rule:fixed(20,'mg','1×/hari; titrasi'),warnings:['Long half-life; interactions and serotonin syndrome considerations.'],status:'Guideline-verified',source:'NICE depression guidance'}),
 r({id:'haloperidol-agitation',drug:'Haloperidol',indication:'Acute severe agitation — selected cases',category:'Psychiatry',population:'Adult',route:'IM',rule:fixed(2.5,'mg','single dose; repeat/titrate per protocol'),warnings:['ECG/QT, EPS, NMS and drug interaction risks; non-pharmacologic de-escalation first when possible.'],status:'Reference-based — verify',source:'NICE violence/aggression guidance'}),
/* DERMATOLOGY */
 r({id:'permethrin-scabies',drug:'Permethrin 5%',indication:'Scabies',category:'Dermatology',population:'Adult + Pediatric',route:'Topical',rule:fixed(1,'application','overnight 8–12 h; repeat after 7 days if needed'),notes:'Treat close contacts and environmental measures according to local guideline.',status:'Guideline-verified',source:'CDC scabies guidance'}),
 r({id:'acyclovir-zoster',drug:'Acyclovir',indication:'Herpes zoster',category:'Infectious',population:'Adult',route:'PO',rule:fixed(800,'mg','5×/hari','7 hari'),warnings:['Best started early; renal adjustment required.'],status:'Guideline-verified',source:'CDC/standard herpes zoster guidance'}),
 r({id:'acyclovir-herpes',drug:'Acyclovir',indication:'First episode genital herpes',category:'Infectious',population:'Adult',route:'PO',rule:fixed(400,'mg','3×/hari','7–10 hari'),status:'Guideline-verified',source:'CDC STI Treatment Guidelines'}),
 r({id:'terbinafine-tinea',drug:'Terbinafine',indication:'Tinea corporis/cruris — systemic selected',category:'Dermatology',population:'Adult',route:'PO',rule:fixed(250,'mg','1×/hari','2–4 minggu'),warnings:['Confirm diagnosis; check hepatic considerations for systemic use.'],status:'Reference-based — verify',source:'Dermatology standard guidance'}),
/* INFECTIOUS / TROPICAL */
 r({id:'dhp-malaria',drug:'Dihydroartemisinin + Piperaquine',indication:'Uncomplicated malaria',category:'Infectious',population:'Adult + Pediatric',route:'PO',rule:mgkgday(4,'mg/kg/day DHA + 18 mg/kg/day piperaquine','1×/hari','3 hari'),notes:'WHO 2025 target dosing; actual tablet number must follow weight band and product strength. Avoid high-fat meals around dosing per product/WHO guidance.',warnings:['P. vivax/ovale requires anti-relapse therapy when indicated; test G6PD where required.'],status:'Guideline-verified',source:'WHO Guidelines for Malaria 2025; Kemenkes malaria guidance'}),
 r({id:'artesunate-severe-malaria',drug:'Artesunate',indication:'Severe malaria',category:'Emergency',population:'Adult + Pediatric',route:'IV/IM',rule:mgkg(2.4,'mg/kg/dose','0, 12, 24 jam lalu 1×/hari sampai oral therapy possible'),warnings:['Severe malaria is an emergency; monitor glucose, parasitemia and hemolysis after therapy.'],status:'Guideline-verified',source:'WHO malaria guidelines 2025'}),
 r({id:'primaquine-vivax',drug:'Primaquine',indication:'P. vivax / P. ovale radical cure',category:'Infectious',population:'Adult + Pediatric',route:'PO',rule:mgkg(0.25,'mg/kg/day','1×/hari','14 hari'),warnings:['Check G6PD status where recommended; contraindications include pregnancy.'],status:'Guideline-verified',source:'WHO malaria guidelines 2025'}),
 r({id:'albendazole-helminth',drug:'Albendazole',indication:'Soil-transmitted helminths selected',category:'Infectious',population:'Adult + Pediatric',route:'PO',rule:fixed(400,'mg','dosis tunggal'),status:'Guideline-verified',source:'WHO neglected tropical disease guidance'}),
 r({id:'praziquantel',drug:'Praziquantel',indication:'Schistosomiasis',category:'Infectious',population:'Adult + Pediatric',route:'PO',rule:mgkg(40,'mg/kg','divided doses same day'),status:'Guideline-verified',source:'WHO schistosomiasis guidance'}),
 r({id:'rifampicin-leprosy',drug:'Rifampicin',indication:'Leprosy — MDT component',category:'Infectious',population:'Adult',route:'PO',rule:fixed(600,'mg','once monthly supervised'),notes:'Must be used as part of multidrug therapy, not monotherapy.',status:'Guideline-verified',source:'WHO leprosy guidance'}),
/* OBGYN */
 r({id:'magnesium-preeclampsia',drug:'Magnesium sulfate',indication:'Severe preeclampsia / eclampsia seizure prevention',category:'OBGYN',population:'Pregnancy',route:'IV/IM',rule:fixed(4,'g','IV loading over ~5 min; maintenance per Zuspan/Pritchard protocol'),warnings:['Monitor RR, patellar reflex, urine output; calcium gluconate antidote available.'],status:'Guideline-verified',source:'WHO recommendations / ACOG obstetric emergency guidance'}),
 r({id:'labetalol-severe-htn-preg',drug:'Labetalol',indication:'Acute severe hypertension in pregnancy',category:'OBGYN',population:'Pregnancy',route:'IV',rule:fixed(20,'mg','initial IV; escalate per protocol'),warnings:['Use institutional acute severe hypertension protocol and monitor BP/HR.'],status:'Guideline-verified',source:'ACOG severe hypertension in pregnancy guidance'}),
 r({id:'nifedipine-severe-htn-preg',drug:'Nifedipine immediate-release',indication:'Acute severe hypertension in pregnancy',category:'OBGYN',population:'Pregnancy',route:'PO',rule:fixed(10,'mg','initial; repeat/titrate per protocol'),warnings:['Do not use sublingual administration.'],status:'Guideline-verified',source:'ACOG severe hypertension in pregnancy guidance'}),
 r({id:'oxytocin-pph',drug:'Oxytocin',indication:'Postpartum haemorrhage due to uterine atony',category:'OBGYN',population:'Pregnancy',route:'IV infusion/IM',rule:fixed(10,'IU','after delivery / infusion per PPH protocol'),warnings:['Follow PPH bundle and uterotonic protocol; dosing varies by route and context.'],status:'Guideline-verified',source:'WHO postpartum haemorrhage guidance'}),
/* EMERGENCY */
 r({id:'epinephrine-anaphylaxis-adult',drug:'Epinephrine',indication:'Anaphylaxis',category:'Emergency',population:'Adult',route:'IM thigh',rule:mgkg(0.01,'mg/kg/dose','repeat every 5–15 min if needed',undefined,0.5),notes:'Use 1 mg/mL (1:1000) solution for IM injection; do not delay.',warnings:['First-line treatment. Airway, oxygen, IV access and monitoring are adjuncts, not substitutes.'],status:'Guideline-verified',source:'WAO anaphylaxis guidance / Resuscitation Council guidance'}),
 r({id:'epinephrine-anaphylaxis-child',drug:'Epinephrine',indication:'Anaphylaxis — child',category:'Emergency',population:'Pediatric',route:'IM thigh',rule:mgkg(0.01,'mg/kg/dose','repeat every 5–15 min if needed',undefined,0.3),warnings:['Use correct concentration and auto-injector/needle for child size.'],status:'Guideline-verified',source:'WAO anaphylaxis guidance'}),
 r({id:'naloxone',drug:'Naloxone',indication:'Opioid-induced respiratory depression',category:'Emergency',population:'Adult',route:'IV/IM/IN',rule:fixed(0.04,'mg','titrate every 2–3 min to adequate ventilation'),warnings:['Goal is adequate ventilation, not necessarily complete arousal; monitor for re-sedation.'],status:'Guideline-verified',source:'AHA/ACLS toxicology guidance'}),
 r({id:'atropine-brady',drug:'Atropine',indication:'Symptomatic bradycardia',category:'Emergency',population:'Adult',route:'IV',rule:fixed(1,'mg','every 3–5 min as needed',undefined,3),status:'Guideline-verified',source:'AHA ACLS 2025'}),
 r({id:'adenosine-svt',drug:'Adenosine',indication:'Regular narrow-complex SVT',category:'Emergency',population:'Adult',route:'IV rapid push',rule:fixed(6,'mg','rapid IV push; then 12 mg if needed'),warnings:['Continuous ECG; proximal IV and flush; avoid in irregular/wide rhythms unless expert protocol.'],status:'Guideline-verified',source:'AHA ACLS 2025'}),
 r({id:'amiodarone-vt',drug:'Amiodarone',indication:'Stable monomorphic VT / refractory VF protocol',category:'Emergency',population:'Adult',route:'IV',rule:fixed(150,'mg','over 10 min for stable VT; protocol differs in cardiac arrest'),warnings:['Use rhythm-specific ACLS protocol. QT, thyroid, hepatic and pulmonary toxicities with longer use.'],status:'Guideline-verified',source:'AHA ACLS 2025'}),
 r({id:'calcium-gluconate-hyperK',drug:'Calcium gluconate',indication:'Hyperkalemia with ECG changes',category:'Emergency',population:'Adult',route:'IV',rule:fixed(10,'mL of 10%','over 2–5 min; repeat guided by ECG'),warnings:['Stabilizes myocardium but does not lower serum potassium; continue definitive potassium-shifting/removal therapy.'],status:'Guideline-verified',source:'UK Kidney Association hyperkalaemia guideline'}),
 r({id:'dextrose-hypoglycemia',drug:'Dextrose',indication:'Severe hypoglycemia in adult unable to take PO',category:'Emergency',population:'Adult',route:'IV',rule:fixed(25,'g','IV, reassess glucose'),warnings:['Recheck glucose and identify cause; concentration depends on local formulation.'],status:'Guideline-verified',source:'ADA Standards of Care 2026'}),
 r({id:'glucagon-hypo',drug:'Glucagon',indication:'Severe hypoglycemia without IV access',category:'Emergency',population:'Adult',route:'IM/SC/IN',rule:fixed(1,'mg','single dose; reassess'),status:'Guideline-verified',source:'ADA Standards of Care 2026'}),
/* RENAL */
 r({id:'allopurinol-gout',drug:'Allopurinol',indication:'Chronic gout urate lowering',category:'Rheumatology',population:'Adult',route:'PO',rule:fixed(100,'mg','1×/hari awal; titrate to urate target'),warnings:['Start low and titrate; consider renal function and HLA-B*58:01 testing in high-risk populations.'],status:'Guideline-verified',source:'ACR gout guidance'}),
 r({id:'colchicine-gout',drug:'Colchicine',indication:'Acute gout selected',category:'Rheumatology',population:'Adult',route:'PO',rule:fixed(1.2,'mg','then 0.6 mg one hour later'),warnings:['Major renal/hepatic and drug-interaction restrictions; avoid repeating high-dose courses.'],status:'Guideline-verified',source:'ACR gout guidance / product labeling'}),
 r({id:'prednisone-gout',drug:'Prednisone',indication:'Acute gout selected',category:'Rheumatology',population:'Adult',route:'PO',rule:fixed(30,'mg','1×/hari','5–10 hari'),status:'Guideline-verified',source:'ACR gout guidance'}),
/* UROLOGY */
 r({id:'tamsulosin',drug:'Tamsulosin',indication:'Lower urinary tract symptoms due to BPH',category:'Urology',population:'Adult',route:'PO',rule:fixed(0.4,'mg','1×/hari setelah makan'),warnings:['Orthostatic hypotension; caution with PDE5 inhibitors.'],status:'Guideline-verified',source:'EAU male LUTS guidance'}),
 r({id:'finasteride',drug:'Finasteride',indication:'BPH with enlarged prostate',category:'Urology',population:'Adult',route:'PO',rule:fixed(5,'mg','1×/hari'),notes:'Clinical benefit takes months; monitor PSA interpretation.',status:'Guideline-verified',source:'EAU male LUTS guidance'}),
/* PEDIATRIC CORE */
 r({id:'diazepam-febrile',drug:'Diazepam',indication:'Prolonged febrile seizure — rescue',category:'Pediatrics',population:'Pediatric',route:'Rectal',rule:mgkg(0.5,'mg/kg/dose','single rescue dose; repeat per protocol',undefined,10),warnings:['First aid and seizure safety remain essential; recurrent/prolonged seizures require emergency evaluation.'],status:'Guideline-verified',source:'Pediatric seizure emergency guidance; kompilasi pengguna'}),
 r({id:'iron-child',drug:'Ferrous sulfate / elemental iron',indication:'Iron deficiency anaemia — child',category:'Pediatrics',population:'Pediatric',route:'PO',rule:mgkgday(3,'mg/kg/day elemental iron','1×/hari or divided','~3 months after Hb correction',200),notes:'Dose is based on elemental iron, not tablet salt weight.',status:'Guideline-verified',source:'WHO pediatric anaemia guidance'}),
 r({id:'amoxicillin-neonate',drug:'Amoxicillin',indication:'Serious bacterial infection — neonate selected',category:'Pediatrics',population:'Neonate',route:'IV',rule:{kind:'protocol',amount:0,unit:'mg/kg',frequency:'Age/postnatal-age and indication dependent'},warnings:['Neonatal dosing requires gestational age, postnatal age, renal function and local neonatal protocol. Do not use a generic pediatric calculator.'],status:'Guideline-verified',source:'WHO serious bacterial infections in infants 0–59 days, 2024'}),
]

export const CATEGORIES = ['All','Antibiotics','Pediatrics','Emergency','Respiratory','Cardiovascular','Neurology','Endocrine','GI','Dermatology','Infectious','Pain','OBGYN','Renal','Psychiatry','Urology','Rheumatology'] as const

export const SOURCE_LIBRARY = [
  'Kompilasi Resep dan Dosis Obat pengguna — reference layer; wajib diverifikasi terhadap guideline terbaru',
  'WHO AWaRe Antibiotic Book + WHO updated infectious disease guidance',
  'WHO Guidelines for Malaria 2025',
  'WHO serious bacterial infections in infants 0–59 days (2024)',
  'IDSA AMR Guidance 2026',
  'IDSA/PIDS CAP in children 2026',
  'GINA Strategy Report 2026',
  'ADA Standards of Care 2026',
  'NICE guidelines (hypertension, UTI, respiratory and other primary-care conditions)',
  'CDC STI Treatment Guidelines',
  'AHA ACLS 2025',
  'ACOG obstetric emergency guidance',
  'ACR gout guidance',
  'EAU urological guidance',
  'Indonesian Ministry of Health / FORNAS KMK HK.01.07/MENKES/1199/2025 for formulary/status cross-check'
]
