import type { DrugRegimen } from './data'
const r=(x:Omit<DrugRegimen,'reviewed'>):DrugRegimen=>({...x,reviewed:'2026-09'})
const f=(amount:number,unit:string,frequency:string,duration?:string,maxDaily?:number)=>({kind:'fixed' as const,amount,unit,frequency,duration,maxDaily})
const k=(amount:number,unit:string,frequency:string,duration?:string,maxDose?:number,maxDaily?:number)=>({kind:'mgkg' as const,amount,unit,frequency,duration,maxDose,maxDaily})
const kd=(amount:number,unit:string,frequency:string,duration?:string,maxDaily?:number)=>({kind:'mgkgday' as const,amount,unit,frequency,duration,maxDaily})
const V=(id:string,drug:string,indication:string,category:DrugRegimen['category'],population:DrugRegimen['population'],route:string,rule:DrugRegimen['rule'],source:string,notes?:string,warnings?:string[])=>r({id,drug,indication,category,population,route,rule,source,status:'Reference-based — verify',notes,warnings})

export const EXTRA_DB:DrugRegimen[]=[
V('acetaminophen-alt','Paracetamol','Pain / fever — adult alternative','Pain','Adult','PO',f(1000,'mg','every 6–8 h PRN',undefined,4000),'Standard analgesic dosing'),
V('naproxen','Naproxen','Acute musculoskeletal pain','Pain','Adult','PO',f(250,'mg','2×/hari','5–7 hari',1000),'Standard NSAID dosing','Use lowest effective dose; GI/renal/CV risks.'),
V('mefenamic','Mefenamic acid','Acute pain / dysmenorrhoea','Pain','Adult','PO',f(500,'mg','3×/hari setelah makan','≤7 hari',1500),'Standard NSAID dosing'),
V('celecoxib','Celecoxib','Acute pain / OA selected','Pain','Adult','PO',f(200,'mg','1×/hari or 100 mg 2×/hari',undefined,400),'Standard COX-2 dosing','CV/renal/GI risk assessment required.'),
V('tramadol','Tramadol','Moderate pain selected','Pain','Adult','PO',f(50,'mg','every 4–6 h PRN',undefined,400),'Product labeling','Serotonin syndrome/seizure/dependence risks.'),
V('buprenorphine','Buprenorphine','Severe pain selected','Pain','Adult','SL/IV',f(0.2,'mg','per protocol','short-term'),'Product labeling','Opioid monitoring required.'),
V('lidocaine','Lidocaine','Local anesthesia','Emergency','Adult + Pediatric','Local',k(4,'mg/kg','single procedure dose',undefined,300),'Standard local anesthetic dosing','Maximum varies with epinephrine and formulation.'),
V('amoxicillin-strep-child','Amoxicillin','Streptococcal pharyngitis — child','Pediatrics','Pediatric','PO',k(50,'mg/kg/day','1×/hari','10 hari',1000),'CDC GAS pharyngitis guidance'),
V('penicillin-gas-child','Penicillin V','Streptococcal pharyngitis — child','Pediatrics','Pediatric','PO',kd(40,'mg/kg/day','2–3 divided doses','10 hari',1000),'CDC GAS pharyngitis guidance'),
V('benzylpenicillin','Benzylpenicillin','Severe susceptible bacterial infection','Antibiotics','Adult','IV',f(2400000,'IU','every 4–6 h according to infection','protocol dependent'),'WHO AWaRe'),
V('ampicillin','Ampicillin','Serious bacterial infection selected','Antibiotics','Adult','IV',f(2000,'mg','every 4–6 h according to indication','protocol dependent'),'WHO AWaRe / IDSA'),
V('ampicillin-neonate','Ampicillin','Neonatal serious bacterial infection','Pediatrics','Neonate','IV',kd(100,'mg/kg/day','divided according to postnatal age','protocol dependent'),'WHO serious bacterial infection guideline 2024','Neonatal dose requires gestational/postnatal age and indication.'),
V('gentamicin-neonate','Gentamicin','Neonatal serious bacterial infection selected','Pediatrics','Neonate','IV/IM',k(5,'mg/kg/dose','interval by postnatal age and renal function'),'WHO serious bacterial infection guideline 2024','Therapeutic monitoring and neonatal protocol required.'),
V('gentamicin-adult','Gentamicin','Serious Gram-negative infection selected','Antibiotics','Adult','IV',k(5,'mg/kg','extended-interval dosing; interval by renal function'),'Product labeling / antimicrobial stewardship','TDM and renal monitoring required.'),
V('amikacin','Amikacin','Resistant Gram-negative infection selected','Antibiotics','Adult','IV/IM',k(15,'mg/kg','extended interval; TDM guided'),'IDSA AMR guidance 2026','Nephro/ototoxicity; reserve for appropriate indications.'),
V('ertapenem','Ertapenem','ESBL infection selected without Pseudomonas risk','Antibiotics','Adult','IV',f(1000,'mg','1×/hari'),'IDSA AMR guidance 2026'),
V('ceftazidime-avibactam','Ceftazidime-avibactam','KPC/selected resistant Gram-negative infection','Antibiotics','Adult','IV',f(2500,'mg','every 8 h over 2 h'),'IDSA AMR guidance 2026','Renal adjustment required; reserve for resistant infections.'),
V('aztreonam','Aztreonam','Selected Gram-negative / MBL combination strategy','Antibiotics','Adult','IV',f(2000,'mg','every 8 h in combination strategy when indicated'),'IDSA AMR guidance 2026','Use only with mechanism-specific expert guidance.'),
V('ceftazidime','Ceftazidime','Pseudomonas infection selected','Antibiotics','Adult','IV',f(2000,'mg','every 8 h'),'WHO AWaRe / IDSA','Renal adjustment required.'),
V('cefuroxime','Cefuroxime','Respiratory/urinary bacterial infection selected','Antibiotics','Adult','PO/IV',f(500,'mg','2×/hari PO'),'WHO AWaRe'),
V('cefixime','Cefixime','Selected uncomplicated bacterial infection','Antibiotics','Adult','PO',f(400,'mg','1×/hari'),'WHO AWaRe','Not preferred for gonorrhea when ceftriaxone available.'),
V('co-trimoxazole-adult','Trimethoprim-sulfamethoxazole','Selected UTI / susceptible infection','Antibiotics','Adult','PO',f(160,'mg TMP component','2×/hari','3–7 hari'),'NICE/WHO antimicrobial guidance','Dose and indication depend on infection; monitor K+/renal function.'),
V('co-trimoxazole-ped','Trimethoprim-sulfamethoxazole','Selected pediatric bacterial infection','Pediatrics','Pediatric','PO',kd(8,'mg/kg/day TMP component','divided 2 doses','indication dependent'),'WHO pediatric antimicrobial guidance'),
V('levofloxacin-cap','Levofloxacin','CAP / respiratory infection selected','Respiratory','Adult','PO/IV',f(750,'mg','1×/hari','5 hari'),'ATS/IDSA CAP guidance','Fluoroquinolone safety restrictions.'),
V('moxifloxacin-cap','Moxifloxacin','CAP selected adult','Respiratory','Adult','PO/IV',f(400,'mg','1×/hari','5 hari'),'ATS/IDSA CAP guidance','QT/tendon/CNS risks.'),
V('doxy-acne','Doxycycline','Moderate–severe inflammatory acne','Dermatology','Adult','PO',f(100,'mg','1–2×/hari','~12 weeks'),'AAD acne guidance','Combine with topical benzoyl peroxide/retinoid; avoid prolonged antibiotic monotherapy.'),
V('clindamycin-topical','Clindamycin','Acne topical selected','Dermatology','Adult + Pediatric','Topical',f(1,'% gel','1×/hari','limited duration'),'AAD acne guidance','Use with benzoyl peroxide to reduce resistance.'),
V('benzoyl-peroxide','Benzoyl peroxide','Acne vulgaris','Dermatology','Adult + Pediatric','Topical',f(2.5,'%','1×/hari','ongoing'),'AAD acne guidance'),
V('tretinoin','Tretinoin','Comedonal acne','Dermatology','Adult + Pediatric','Topical',f(0.025,'%','nightly','ongoing'),'AAD acne guidance','Irritation and photosensitivity counseling.'),
V('hydrocortisone-topical','Hydrocortisone 1%','Mild inflammatory dermatitis','Dermatology','Adult + Pediatric','Topical',f(1,'%','1–2×/hari','short course'),'Dermatology standard guidance'),
V('mometasone-topical','Mometasone furoate','Inflammatory dermatitis selected','Dermatology','Adult + Pediatric','Topical',f(0.1,'%','1×/hari','short course'),'Dermatology standard guidance','Avoid prolonged/high-potency use on face/folds.'),
V('clobetasol','Clobetasol','Severe localized dermatitis selected','Dermatology','Adult','Topical',f(0.05,'%','1–2×/hari','≤2 weeks'),'Dermatology standard guidance','Super-potent steroid; limit duration and site.'),
V('cetirizine','Cetirizine','Allergic rhinitis / urticaria','Dermatology','Adult','PO',f(10,'mg','1×/hari'),'ARIA / allergy guidance'),
V('cetirizine-child','Cetirizine','Allergic symptoms — child','Pediatrics','Pediatric','PO',k(0.25,'mg/kg/day','1×/hari',undefined,10),'Pediatric product labeling'),
V('loratadine','Loratadine','Allergic rhinitis / urticaria','Respiratory','Adult','PO',f(10,'mg','1×/hari'),'ARIA allergy guidance'),
V('fluticasone-nasal','Fluticasone nasal','Allergic rhinitis','Respiratory','Adult','Intranasal',f(2,'sprays/nostril','1×/hari','until controlled'),'ARIA guidance'),
V('oxymetazoline','Oxymetazoline','Nasal congestion short-term','Respiratory','Adult','Intranasal',f(1,'spray/nostril','2×/hari','≤3 days'),'Standard decongestant guidance','Avoid prolonged use due rebound congestion.'),
V('budesonide-neb','Budesonide','Asthma controller selected','Respiratory','Pediatric','Nebulized',f(0.5,'mg','1–2×/hari','per asthma plan'),'GINA 2026'),
V('tiotropium','Tiotropium','COPD maintenance','Respiratory','Adult','Inhaled',f(18,'mcg','1×/hari'),'GOLD strategy'),
V('formoterol','Formoterol','COPD maintenance selected','Respiratory','Adult','Inhaled',f(12,'mcg','2×/hari','per product'),'GOLD strategy'),
V('budesonide-copd','Budesonide/formoterol','COPD selected with ICS indication','Respiratory','Adult','Inhaled',f(1,'inhalation','2×/hari'),'GOLD strategy','ICS use should be phenotype/exacerbation guided.'),
V('oseltamivir-adult','Oseltamivir','Influenza treatment','Infectious','Adult','PO',f(75,'mg','2×/hari','5 hari'),'CDC influenza antiviral guidance'),
V('oseltamivir-child','Oseltamivir','Influenza treatment — child','Pediatrics','Pediatric','PO',k(3,'mg/kg/dose','2×/hari','5 hari',75),'CDC influenza antiviral guidance'),
V('acyclovir-varicella','Acyclovir','Varicella selected adult','Infectious','Adult','PO',f(800,'mg','5×/hari','5–7 hari'),'CDC/standard herpes guidance'),
V('valacyclovir-zoster','Valacyclovir','Herpes zoster','Infectious','Adult','PO',f(1000,'mg','3×/hari','7 hari'),'CDC herpes guidance'),
V('fluconazole-vvc','Fluconazole','Uncomplicated vulvovaginal candidiasis','OBGYN','Adult','PO',f(150,'mg','single dose'),'CDC STI Treatment Guidelines','Avoid oral fluconazole in pregnancy; use topical azole in pregnancy.'),
V('clotrimazole-vvc','Clotrimazole','Vulvovaginal candidiasis','OBGYN','Pregnancy','Intravaginal',f(500,'mg','single dose'),'CDC STI Treatment Guidelines'),
V('metronidazole-bv','Metronidazole','Bacterial vaginosis','OBGYN','Adult','PO',f(500,'mg','2×/hari','7 hari'),'CDC STI Treatment Guidelines'),
V('metronidazole-trich','Metronidazole','Trichomoniasis — woman','OBGYN','Adult','PO',f(500,'mg','2×/hari','7 hari'),'CDC STI Treatment Guidelines'),
V('doxy-pid','Doxycycline','Pelvic inflammatory disease component','OBGYN','Adult','PO',f(100,'mg','2×/hari','14 hari'),'CDC STI Treatment Guidelines','Use as part of combination regimen with ceftriaxone + metronidazole when indicated.'),
V('ceftriaxone-pid','Ceftriaxone','PID outpatient component','OBGYN','Adult','IM',f(500,'mg','single dose'),'CDC STI Treatment Guidelines','Combination regimen required.'),
V('levonorgestrel-ec','Levonorgestrel','Emergency contraception','OBGYN','Adult','PO',f(1.5,'mg','single dose'),'WHO/ACOG contraception guidance'),
V('misoprostol-pph','Misoprostol','Postpartum haemorrhage uterotonic selected','OBGYN','Pregnancy','PO/SL/PR',f(800,'mcg','single dose per PPH protocol'),'WHO PPH guidance','Use within PPH bundle; route/dose protocol dependent.'),
V('oxytocin-induction','Oxytocin','Labour induction/augmentation','OBGYN','Pregnancy','IV infusion',f(1,'mU/min','start low, titrate per contraction/FHR protocol'),'WHO intrapartum care guidance','Must be infusion-pump/protocol controlled.'),
V('insulin-regular','Regular insulin','Prandial/correction insulin selected','Endocrine','Adult','SC',f(4,'units','individualized before meals/correction'),'ADA Standards of Care 2026','Dose must be individualized to glucose, intake and regimen.'),
V('insulin-lispro','Insulin lispro','Mealtime insulin','Endocrine','Adult','SC',f(4,'units','individualized with meals'),'ADA Standards of Care 2026'),
V('glargine-child','Insulin glargine','Basal insulin — pediatric diabetes','Endocrine','Pediatric','SC',k(0.1,'unit/kg','1×/hari awal; titrasi'),'ADA pediatric diabetes guidance','Individualize to total daily insulin regimen.'),
V('glucagon-ped','Glucagon','Severe hypoglycemia — child','Pediatrics','Pediatric','IM/SC/IN',k(0.03,'mg/kg','single dose',undefined,1),'ADA/pediatric emergency guidance'),
V('levothyroxine','Levothyroxine','Primary hypothyroidism','Endocrine','Adult','PO',f(25,'mcg','1×/hari initial in older/cardiac patients; titrate'),'ATA hypothyroidism guidance'),
V('levothyroxine-child','Levothyroxine','Hypothyroidism — child','Pediatrics','Pediatric','PO',kd(4,'mcg/kg/day','1×/hari; age-dependent'),'ATA/AAP pediatric thyroid guidance'),
V('carbimazole','Carbimazole','Hyperthyroidism','Endocrine','Adult','PO',f(15,'mg','1×/hari initial; titrate'),'Thyroid association guidance'),
V('propranolol-hyperthyroid','Propranolol','Hyperthyroid symptom control','Endocrine','Adult','PO',f(20,'mg','3–4×/hari; titrate'),'ATA hyperthyroidism guidance','Avoid/caution in asthma and bradycardia.'),
V('calcium-carbonate','Calcium carbonate','Calcium supplementation','Endocrine','Adult','PO',f(500,'mg elemental calcium','1–2×/hari with food'),'Standard mineral supplementation'),
V('alendronate','Alendronate','Osteoporosis','Endocrine','Adult','PO',f(70,'mg','once weekly'),'NOF/osteoporosis guidance','Take fasting with water and remain upright.'),
V('vitamin-d','Cholecalciferol','Vitamin D deficiency selected','Endocrine','Adult','PO',f(1000,'IU','1×/hari; adjust to level'),'Endocrine/osteoporosis guidance'),
V('atorvastatin-high','Atorvastatin','High-intensity lipid lowering','Cardiovascular','Adult','PO',f(80,'mg','1×/hari'),'ACC/AHA lipid guidance'),
V('rosuvastatin','Rosuvastatin','Dyslipidemia / ASCVD prevention','Cardiovascular','Adult','PO',f(20,'mg','1×/hari'),'ACC/AHA lipid guidance'),
V('ezetimibe','Ezetimibe','LDL lowering adjunct','Cardiovascular','Adult','PO',f(10,'mg','1×/hari'),'ACC/AHA lipid guidance'),
V('hydrochlorothiazide','Hydrochlorothiazide','Hypertension','Cardiovascular','Adult','PO',f(12.5,'mg','1×/hari'),'NICE/ACC hypertension guidance'),
V('indapamide','Indapamide','Hypertension','Cardiovascular','Adult','PO',f(1.25,'mg','1×/hari'),'NICE NG136'),
V('carvedilol','Carvedilol','HFrEF / heart failure selected','Cardiovascular','Adult','PO',f(3.125,'mg','2×/hari initial; titrate'),'ESC heart failure guidance'),
V('sacubitril-valsartan','Sacubitril/valsartan','HFrEF selected','Cardiovascular','Adult','PO',f(24/26,'mg','2×/hari initial; titrate'),'ESC heart failure guidance','Requires ACE inhibitor washout when switching from ACEi.'),
V('dapagliflozin-hf','Dapagliflozin','Heart failure cardiorenal therapy','Cardiovascular','Adult','PO',f(10,'mg','1×/hari'),'ADA 2026 / ESC heart failure guidance'),
V('apixaban-af','Apixaban','Stroke prevention in nonvalvular AF','Cardiovascular','Adult','PO',f(5,'mg','2×/hari'),'ESC/ACC atrial fibrillation guidance','Dose reduction depends on age, weight, creatinine and label criteria.'),
V('warfarin','Warfarin','Anticoagulation selected','Cardiovascular','Adult','PO',f(5,'mg','individualized; INR guided'),'ACC/ESC anticoagulation guidance','No fixed dose calculator; INR-guided titration essential.'),
V('enoxaparin-vte','Enoxaparin','VTE treatment selected','Cardiovascular','Adult','SC',k(1,'mg/kg','every 12 h'),'CHEST/anticoagulation guidance','Renal adjustment required.'),
V('enoxaparin-proph','Enoxaparin','VTE prophylaxis hospitalized adult','Cardiovascular','Adult','SC',f(40,'mg','1×/hari'),'Standard hospital VTE prophylaxis','Renal/weight adjustment may be required.'),
V('heparin-vte','Unfractionated heparin','Acute VTE treatment','Emergency','Adult','IV infusion',k(80,'units/kg bolus','then 18 units/kg/h; aPTT/anti-Xa guided'),'CHEST anticoagulation guidance'),
V('alteplase-stroke','Alteplase','Acute ischemic stroke thrombolysis selected','Emergency','Adult','IV',k(0.9,'mg/kg','10% bolus then remainder over 60 min',undefined,90),'AHA/ASA stroke guidance','Strict eligibility/time/imaging criteria required; not a generic dose-only tool.'),
V('tenecteplase-stroke','Tenecteplase','Acute ischemic stroke thrombolysis selected','Emergency','Adult','IV',k(0.25,'mg/kg','single bolus',undefined,25),'AHA/ASA stroke guidance','Eligibility and imaging criteria mandatory.'),
V('nicardipine','Nicardipine','Acute severe hypertension / neurocritical BP control','Emergency','Adult','IV infusion',f(5,'mg/h','start; titrate every 5–15 min'),'AHA stroke/emergency BP guidance'),
V('labetalol','Labetalol','Acute severe hypertension selected','Emergency','Adult','IV',f(10,'mg','bolus; repeat/titrate per protocol'),'AHA/ACC emergency BP guidance'),
V('furosemide-edema','Furosemide','Acute pulmonary edema/congestion','Emergency','Adult','IV',f(40,'mg','initial; titrate to response'),'Heart failure/emergency guidance'),
V('nitroprusside','Sodium nitroprusside','Hypertensive emergency selected','Emergency','Adult','IV infusion',f(0.3,'mcg/kg/min','titrate under ICU monitoring'),'Critical care hypertension guidance','Cyanide/thiocyanate toxicity risk; specialist use.'),
V('magnesium-asthma','Magnesium sulfate','Severe asthma exacerbation selected','Emergency','Adult','IV',f(2,'g','over ~20 min single dose'),'GINA 2026'),
V('magnesium-eclampsia','Magnesium sulfate','Eclampsia','OBGYN','Pregnancy','IV/IM',f(4,'g','IV loading; maintenance per protocol'),'WHO/ACOG obstetric guidance'),
V('calcium-chloride','Calcium chloride','Cardiac arrest / severe hyperkalemia selected','Emergency','Adult','IV',f(1,'g','10% solution per resuscitation protocol'),'AHA ACLS 2025','Use central access when appropriate; concentration differs from calcium gluconate.'),
V('sodium-bicarbonate','Sodium bicarbonate','Selected toxicologic/metabolic emergencies','Emergency','Adult','IV',f(50,'mEq','protocol guided'),'AHA/critical care guidance','Not routine cardiac arrest therapy; indication-specific.'),
V('thiamine','Thiamine','Alcohol-related deficiency / Wernicke risk','Emergency','Adult','IV/IM',f(200,'mg','1–3×/hari depending indication'),'Neurology/addiction medicine guidance'),
V('haloperidol-delirium','Haloperidol','Severe delirium agitation selected','Psychiatry','Adult','PO/IM',f(0.5,'mg','low dose; titrate to response'),'NICE delirium guidance','QT/EPS/NMS risks; address underlying cause.'),
V('lorazepam','Lorazepam','Acute severe anxiety / catatonia selected','Psychiatry','Adult','PO/IM',f(0.5,'mg','1–2×/hari short-term'),'NICE anxiety guidance','Dependence/sedation; short duration.'),
V('clonazepam','Clonazepam','Panic disorder selected','Psychiatry','Adult','PO',f(0.25,'mg','2×/hari short-term'),'NICE panic guidance','Not first-line long-term; dependence risk.'),
V('quetiapine','Quetiapine','Schizophrenia/bipolar selected','Psychiatry','Adult','PO',f(50,'mg','titration schedule required'),'NICE psychosis/bipolar guidance','Metabolic, QT and sedation monitoring.'),
V('risperidone','Risperidone','Psychosis selected','Psychiatry','Adult','PO',f(1,'mg','1–2×/hari; titrate'),'NICE psychosis guidance','Monitor EPS, prolactin and metabolic effects.'),
V('amitriptyline','Amitriptyline','Neuropathic pain / migraine prevention','Neurology','Adult','PO',f(10,'mg','at night; titrate'),'Neuropathic pain guidance','Anticholinergic and cardiac risks.'),
V('pregabalin','Pregabalin','Neuropathic pain selected','Neurology','Adult','PO',f(75,'mg','2×/hari; titrate'),'Neuropathic pain guidance','Renal adjustment and sedation risk.'),
V('topiramate','Topiramate','Migraine prevention / epilepsy selected','Neurology','Adult','PO',f(25,'mg','at night; titrate'),'AHS/neurology guidance','Cognitive effects, stones, pregnancy risk.'),
V('phenytoin','Phenytoin','Status epilepticus maintenance selected','Neurology','Adult','IV/PO',k(15,'mg/kg','loading under ECG/BP monitoring'),'AES/ILAE status epilepticus guidance','Complex kinetics; specialist dosing/TDM.'),
V('phenobarbital','Phenobarbital','Seizure emergency selected','Neurology','Pediatric','IV/IM',k(20,'mg/kg','loading per status protocol'),'WHO/AES pediatric seizure guidance'),
V('levetiracetam-load','Levetiracetam','Status epilepticus second-line selected','Emergency','Adult','IV',k(60,'mg/kg','single loading dose',undefined,4500),'AES status epilepticus guidance'),
V('mannitol','Mannitol','Raised intracranial pressure selected','Emergency','Adult','IV',k(0.25,'g/kg','over 20 min; repeat guided by ICP/osmolality'),'Neurocritical care guidance','Monitor osmolality, renal function and volume status.'),
V('dexamethasone-brain','Dexamethasone','Vasogenic edema from brain tumor selected','Neurology','Adult','IV/PO',f(4,'mg','every 6–12 h; specialist guided'),'Neuro-oncology guidance'),
V('omeprazole-hp','Omeprazole','H. pylori eradication component','GI','Adult','PO',f(20,'mg','2×/hari as part of combination regimen','14 hari'),'ACG H. pylori guidance 2024','Use complete contemporary eradication regimen; not PPI monotherapy.'),
V('bismuth','Bismuth subsalicylate','H. pylori bismuth quadruple component','GI','Adult','PO',f(524,'mg','4×/hari','14 hari'),'ACG H. pylori guidance 2024'),
V('famotidine','Famotidine','GERD/dyspepsia selected','GI','Adult','PO',f(20,'mg','1–2×/hari'),'ACG GERD guidance'),
V('sucralfate','Sucralfate','Duodenal ulcer selected','GI','Adult','PO',f(1,'g','4×/hari','4–8 minggu'),'Gastroenterology standard guidance'),
V('lactulose','Lactulose','Constipation / hepatic encephalopathy','GI','Adult','PO',f(15,'mL','1–2×/hari constipation; titrate for 2–3 soft stools/day HE'),'AASLD hepatic encephalopathy guidance'),
V('polyethylene-glycol','Polyethylene glycol','Constipation','GI','Adult','PO',f(17,'g','1×/hari'),'GI constipation guidance'),
V('bisacodyl','Bisacodyl','Constipation short-term','GI','Adult','PO',f(5,'mg','1×/hari at night'),'Constipation guidance'),
V('metoclopramide','Metoclopramide','Nausea/vomiting selected','GI','Adult','PO/IV',f(10,'mg','up to 3×/hari; short course'),'Product labeling','EPS/tardive dyskinesia risk; duration limits apply.'),
V('dimenhydrinate','Dimenhydrinate','Motion sickness/vertigo symptoms','GI','Adult','PO',f(50,'mg','every 4–6 h PRN'),'Standard antiemetic guidance','Sedation/anticholinergic effects.'),
V('mesalazine','Mesalazine','Ulcerative colitis mild–moderate','GI','Adult','PO',f(2400,'mg','daily divided according to formulation'),'ACG ulcerative colitis guidance','Formulation-specific dosing.'),
V('prednisolone-ibd','Prednisolone','IBD flare selected','GI','Adult','PO',f(40,'mg','1×/hari; taper after response'),'ACG IBD guidance','Steroid induction, not maintenance.'),
V('metronidazole-amoeba','Metronidazole','Amoebic colitis selected','Infectious','Adult','PO',f(750,'mg','3×/hari','5–10 hari'),'WHO/IDSA infectious diarrhoea guidance'),
V('tinidazole','Tinidazole','Giardiasis/trichomoniasis selected','Infectious','Adult','PO',f(2000,'mg','single dose or indication-specific'),'CDC/WHO STI/parasite guidance'),
V('pyrantel','Pyrantel','Enterobiasis/soil-transmitted helminths','Infectious','Adult + Pediatric','PO',k(11,'mg/kg','single dose; repeat for pinworm per protocol',undefined,1000),'CDC/WHO parasite guidance'),
V('ivermectin','Ivermectin','Strongyloidiasis/scabies selected','Infectious','Adult','PO',k(200,'mcg/kg','1×/hari; duration indication-dependent'),'CDC parasite guidance','Pregnancy and weight/age restrictions apply.'),
V('diethylcarbamazine','Diethylcarbamazine','Lymphatic filariasis selected','Infectious','Adult','PO',f(6,'mg/kg/day','divided 3 doses','12 hari'),'WHO lymphatic filariasis guidance'),
V('isoniazid','Isoniazid','TB treatment component / preventive therapy','Infectious','Adult','PO',f(300,'mg','1×/hari','regimen dependent'),'WHO TB guidance','Always use appropriate combination regimen when treating active TB; monitor hepatotoxicity.'),
V('rifampicin','Rifampicin','TB treatment component','Infectious','Adult','PO',k(10,'mg/kg','1×/hari','regimen dependent',600),'WHO TB guidance'),
V('pyrazinamide','Pyrazinamide','TB treatment component','Infectious','Adult','PO',k(25,'mg/kg','1×/hari','regimen dependent'),'WHO TB guidance'),
V('ethambutol','Ethambutol','TB treatment component','Infectious','Adult','PO',k(15,'mg/kg','1×/hari','regimen dependent'),'WHO TB guidance','Visual acuity/color monitoring.'),
V('pyridoxine-tb','Pyridoxine','INH neuropathy prevention selected','Infectious','Adult','PO',f(25,'mg','1×/hari during isoniazid therapy'),'WHO TB guidance'),
V('artemisinin-piperaquine','DHP','Malaria uncomplicated weight-band regimen','Infectious','Adult + Pediatric','PO',kd(4,'mg/kg/day DHA + 18 mg/kg/day piperaquine','1×/hari','3 hari'),'WHO malaria guidelines 2025','Actual tablets must be selected by weight band/product strength.'),
V('primaquine-falciparum','Primaquine','P. falciparum gametocytocidal dose where indicated','Infectious','Adult','PO',f(0.75,'mg/kg','single dose'),'WHO malaria guidelines 2025','Follow current national policy and G6PD considerations.'),
V('cefuroxime-uti-preg','Cefuroxime','Pregnancy UTI selected','OBGYN','Pregnancy','PO',f(250,'mg','2×/hari','7 hari'),'NICE NG109'),
V('nitrofurantoin-preg','Nitrofurantoin','Lower UTI in pregnancy selected','OBGYN','Pregnancy','PO',f(100,'mg','2×/hari','7 hari'),'NICE NG109','Avoid near term according to local guidance/label; not for pyelonephritis.'),
V('ferrous-sulfate','Ferrous sulfate','Iron deficiency anaemia — adult','Endocrine','Adult','PO',f(200,'mg ferrous sulfate','1×/hari or alternate day according to tolerance'),'BSH/iron deficiency guidance','Dose is salt-specific; elemental iron content varies.'),
V('folic-acid','Folic acid','Folate deficiency / preconception','OBGYN','Adult','PO',f(400,'mcg','1×/hari'),'WHO/ACOG folic acid guidance'),
V('folic-acid-high-risk','Folic acid','High-risk neural tube defect prevention','OBGYN','Pregnancy','PO',f(5,'mg','1×/hari','preconception through first trimester'),'NICE/ACOG high-risk folate guidance'),
V('calcium-preg','Calcium','Pregnancy calcium supplementation where dietary intake low','OBGYN','Pregnancy','PO',f(1500,'mg elemental/day','divided doses'),'WHO pregnancy calcium guidance'),
V('aspirin-preeclampsia','Low-dose aspirin','Preeclampsia prevention high-risk pregnancy','OBGYN','Pregnancy','PO',f(81,'mg','1×/hari'),'ACOG preeclampsia prevention guidance'),
V('labetalol-preg','Labetalol','Chronic hypertension in pregnancy','OBGYN','Pregnancy','PO',f(100,'mg','2×/hari; titrate'),'ACOG hypertension in pregnancy guidance'),
V('nifedipine-xl','Nifedipine ER','Chronic hypertension in pregnancy','OBGYN','Pregnancy','PO',f(30,'mg','1×/hari; titrate'),'ACOG hypertension in pregnancy guidance'),
V('methyldopa','Methyldopa','Hypertension in pregnancy selected','OBGYN','Pregnancy','PO',f(250,'mg','2–3×/hari; titrate'),'Obstetric hypertension guidance'),
V('terbutaline','Terbutaline','Tocolysis selected','OBGYN','Pregnancy','SC/IV',f(0.25,'mg','single/repeat per specialist protocol'),'Obstetric emergency guidance','Specialist use only; maternal/fetal monitoring.'),
V('dexamethasone-fetal','Dexamethasone','Antenatal corticosteroid selected','OBGYN','Pregnancy','IM',f(6,'mg','every 12 h ×4 doses'),'WHO preterm birth guidance'),
V('tranexamic-pph','Tranexamic acid','Postpartum haemorrhage','OBGYN','Pregnancy','IV',f(1000,'mg','as early as possible within 3 h of birth; repeat once if indicated'),'WHO PPH guidance'),
V('tranexamic-trauma','Tranexamic acid','Major trauma bleeding selected','Emergency','Adult','IV',f(1000,'mg','over 10 min then 1 g over 8 h'),'CRASH-2 / trauma guidance'),
V('cefazolin-proph','Cefazolin','Surgical antimicrobial prophylaxis selected','Emergency','Adult','IV',f(2000,'mg','within 60 min before incision'),'ASHP surgical prophylaxis guidance'),
V('cefazolin-ped','Cefazolin','Surgical prophylaxis — child','Pediatrics','Pediatric','IV',k(30,'mg/kg','within 60 min before incision',undefined,2000),'ASHP pediatric surgical prophylaxis guidance'),
V('tetanus-ig','Tetanus immunoglobulin','Tetanus-prone wound prophylaxis selected','Emergency','Adult + Pediatric','IM',f(250,'IU','single dose; wound-dependent'),'CDC tetanus wound guidance'),
V('tetanus-vaccine','Tetanus-containing vaccine','Wound prophylaxis','Emergency','Adult + Pediatric','IM',f(0.5,'mL','single dose when indicated'),'CDC wound management guidance'),
V('epinephrine-croup','Epinephrine','Severe croup with stridor at rest','Pediatrics','Pediatric','Nebulized',f(5,'mL of 1 mg/mL','single nebulized dose; repeat per protocol'),'Pediatric emergency guidance','Observe for recurrence and treat with corticosteroid.'),
V('dexamethasone-croup','Dexamethasone','Croup','Pediatrics','Pediatric','PO/IM/IV',k(0.6,'mg/kg','single dose',undefined,10),'Pediatric croup guidance'),
V('amoxicillin-sinus','Amoxicillin','Acute bacterial rhinosinusitis selected','Respiratory','Adult','PO',f(875,'mg','2×/hari','5–7 hari'),'IDSA/AAO-HNS sinusitis guidance'),
V('doxy-sinus','Doxycycline','Acute bacterial rhinosinusitis penicillin allergy selected','Respiratory','Adult','PO',f(100,'mg','2×/hari','5–7 hari'),'IDSA sinusitis guidance'),
V('prednisolone-bell','Prednisolone','Bell palsy early treatment','Neurology','Adult','PO',f(60,'mg','1×/hari','5 hari then taper protocol'),'AAO-HNS Bell palsy guidance'),
V('acyclovir-bell','Acyclovir','Bell palsy antiviral selected','Neurology','Adult','PO',f(400,'mg','5×/hari','7–10 hari'),'AAO-HNS Bell palsy guidance','Antiviral is adjunct in selected cases, not substitute for steroid.'),
V('aspirin-tia','Aspirin','TIA/minor ischemic stroke antiplatelet','Neurology','Adult','PO',f(160,'mg','initial then maintenance per stroke protocol'),'AHA/ASA stroke guidance'),
V('clopidogrel-tia','Clopidogrel','Minor stroke/TIA DAPT selected','Neurology','Adult','PO',f(75,'mg','1×/hari after loading when indicated'),'AHA/ASA stroke guidance','DAPT duration is indication-specific.'),
V('atorvastatin-stroke','Atorvastatin','Secondary prevention after ischemic stroke','Neurology','Adult','PO',f(80,'mg','1×/hari'),'AHA/ASA secondary stroke prevention'),
V('lisinopril-stroke','Lisinopril','Secondary hypertension prevention after stroke','Neurology','Adult','PO',f(10,'mg','1×/hari; titrate'),'AHA/ASA secondary prevention'),
V('tamsulosin-stone','Tamsulosin','Ureteric stone selected expulsive therapy','Urology','Adult','PO',f(0.4,'mg','1×/hari','short-term'),'EAU urolithiasis guidance','Evidence depends on stone size/location; not for all stones.'),
V('diclofenac-renal-colic','Diclofenac','Renal colic','Urology','Adult','PO/IM',f(50,'mg','2–3×/hari PRN','short course',150),'EAU urolithiasis guidance','Avoid in renal impairment/GI bleeding.'),
V('finasteride-bph','Finasteride','BPH with enlarged prostate','Urology','Adult','PO',f(5,'mg','1×/hari'),'EAU male LUTS guidance'),
V('tadalafil-bph','Tadalafil','BPH LUTS selected','Urology','Adult','PO',f(5,'mg','1×/hari'),'EAU male LUTS guidance','Contraindicated with nitrates.'),
V('oxybutynin','Oxybutynin','Overactive bladder selected','Urology','Adult','PO',f(5,'mg','2–3×/hari'),'EAU female LUTS guidance','Anticholinergic burden and retention risk.'),
V('tadalafil-ed','Tadalafil','Erectile dysfunction','Urology','Adult','PO',f(10,'mg','as needed ≥30 min before activity'),'EAU sexual/reproductive guidance','Never combine with nitrates.'),
V('allopurinol-start','Allopurinol','Gout urate lowering initiation','Rheumatology','Adult','PO',f(100,'mg','1×/hari; titrate every 2–5 weeks'),'ACR gout guidance'),
V('colchicine-proph','Colchicine','Gout flare prophylaxis during ULT initiation','Rheumatology','Adult','PO',f(0.6,'mg','1×/hari or 2×/hari'),'ACR gout guidance','Renal/hepatic and interaction restrictions.'),
V('prednisolone-ra','Prednisolone','Inflammatory arthritis flare selected','Rheumatology','Adult','PO',f(10,'mg','1×/hari short course'),'Rheumatology standard guidance'),
V('hydroxychloroquine','Hydroxychloroquine','SLE/RA selected','Rheumatology','Adult','PO',f(200,'mg','1–2×/hari'),'EULAR rheumatology guidance','Retinal screening and weight-based safety.'),
V('epinephrine-autoinjector','Epinephrine','Anaphylaxis outpatient rescue','Emergency','Adult + Pediatric','IM auto-injector',f(0.3,'mg','single dose; repeat per emergency plan'),'WAO anaphylaxis guidance'),
V('dexamethasone-severe','Dexamethasone','Cerebral edema / selected emergencies','Emergency','Adult','IV/PO',f(10,'mg','initial then protocol dependent'),'Neurocritical care guidance'),
V('normal-saline','Sodium chloride 0.9%','Selected resuscitation / replacement','Emergency','Adult + Pediatric','IV',f(500,'mL','bolus/replacement according to response'),'NICE fluid therapy / Surviving Sepsis 2026','Balanced crystalloid is preferred in many sepsis settings; fluid choice is context-specific.'),
V('balanced-crystalloid','Balanced crystalloid','Sepsis/hypovolemia resuscitation','Emergency','Adult + Pediatric','IV',f(500,'mL','bolus then reassess perfusion/fluid tolerance'),'Surviving Sepsis Campaign 2026','Individualize volume and reassess after each bolus.'),
V('albumin-sepsis','Albumin','Selected sepsis fluid after substantial crystalloid','Emergency','Adult','IV',f(20,'% solution','individualized after crystalloid'),'Surviving Sepsis Campaign 2026','Not routine first-line fluid; assess context.'),
]
